(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.KoineAdaptiveReview=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const STORAGE_KEY='koine-path-adaptive-review-v1',SCHEMA=1,DEFAULT_MINUTES=20,MAX_HISTORY=120;
const COST={remediation:3,'unit-review':4,vocabulary:.6,morphology:2.5,syntax:3.5,reading:5};
const clone=v=>JSON.parse(JSON.stringify(v));const safe=s=>{try{return JSON.parse(s)}catch{return null}};const iso=d=>new Date(d).toISOString();const days=(a,b)=>Math.max(0,(new Date(b)-new Date(a))/86400000);
class MemoryStorage{constructor(seed={}){this.m=new Map(Object.entries(seed))}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.m.set(k,String(v))}}
function initial(now){return{schemaVersion:SCHEMA,settings:{dailyMinutes:DEFAULT_MINUTES,maxTasks:28},activeSession:null,history:[],createdAt:iso(now),updatedAt:iso(now)}}
function domainForSource(source=''){source=String(source);if(source.includes('vocab'))return'vocabulary';if(source.includes('morph'))return'morphology';if(source.includes('syntax'))return'syntax';if(source.includes('reader')||source.includes('reading')||source.includes('fluency'))return'reading';return'remediation'}
function viewForUnit(id){id=Number(id);if(id>=45)return'fluency';if(id>=38)return'syntax';if(id>=5)return'drill';return'learn'}
function learningViewForUnit(id){id=Number(id);if(id>=45)return'fluency';if(id>=38)return'syntax';return'learn'}
function memoryEstimate(unit,now){if(!unit)return{stabilityDays:1,elapsedDays:0,retrievability:1,risk:0};const last=[...Object.values(unit.dimensions||{}).map(x=>x.lastAt).filter(Boolean),unit.lastActivityAt].filter(Boolean).sort().at(-1);const elapsed=last?days(last,now):0;const stability=Math.max(1,(unit.reviewIntervalDays||14)*(.55+(Number(unit.composite)||0)/180));let retrievability=Math.exp(-elapsed/stability);if(unit.reviewDue)retrievability=Math.min(retrievability,.45);return{stabilityDays:Math.round(stability*10)/10,elapsedDays:Math.round(elapsed*10)/10,retrievability:Math.round(retrievability*100)/100,risk:Math.round((1-retrievability)*100)/100}}
class AdaptiveReviewEngine{
 constructor({learningEngine,vocabularyEngine=null,morphologyLab=null,syntaxEngine=null,storage=null,clock=()=>new Date()}={}){if(!learningEngine)throw new Error('AdaptiveReviewEngine requires learningEngine');this.learning=learningEngine;this.vocab=vocabularyEngine;this.morph=morphologyLab;this.syntax=syntaxEngine;this.storage=storage||((typeof localStorage!=='undefined')?localStorage:new MemoryStorage());this.clock=clock;this.state={...initial(clock()),...(safe(this.storage.getItem(STORAGE_KEY))||{})};this.state.settings={...initial(clock()).settings,...(this.state.settings||{})};this.persist()}
 persist(){this.state.updatedAt=iso(this.clock());this.storage.setItem(STORAGE_KEY,JSON.stringify(this.state))}
 snapshot(){return clone(this.state)}
 setDailyMinutes(n){this.state.settings.dailyMinutes=Math.max(5,Math.min(90,Number(n)||DEFAULT_MINUTES));this.persist();return this.state.settings.dailyMinutes}
 errorClusters(){const s=this.learning.snapshot(),open=(s.remediation||[]).filter(r=>r.status==='open'),map=new Map();for(const r of open){const k=`${r.unitId}:${r.type}`,x=map.get(k)||{unitId:r.unitId,type:r.type,occurrences:0,items:0,sources:{},lastAt:r.lastAt};x.occurrences+=Number(r.occurrences)||1;x.items++;x.sources[r.source]=(x.sources[r.source]||0)+1;if(new Date(r.lastAt)>new Date(x.lastAt))x.lastAt=r.lastAt;map.set(k,x)}return[...map.values()].sort((a,b)=>b.occurrences-a.occurrences||new Date(b.lastAt)-new Date(a.lastAt))}
 remediationTasks(){return this.errorClusters().map(c=>{const source=Object.entries(c.sources).sort((a,b)=>b[1]-a[1])[0]?.[0]||'',domain=domainForSource(source),unit=this.learning.getUnit(c.unitId),age=days(c.lastAt,this.clock());const escalation=c.occurrences>=6?'persistent':c.occurrences>=3?'repeated':'new';const priority=Math.min(120,94+c.occurrences*4+(unit?.reviewDue?8:0)+Math.min(6,age*.3));return{id:`rem.${c.unitId}.${c.type}`,kind:'remediation',domain,view:domain==='remediation'?viewForUnit(c.unitId):domain==='vocabulary'?'vocab':domain==='morphology'?'drill':domain==='syntax'?'syntax':'fluency',unitId:c.unitId,title:`Repair ${String(c.type).replaceAll('_',' ')}`,reason:`${c.occurrences} occurrence${c.occurrences===1?'':'s'} across ${c.items} open item${c.items===1?'':'s'} · ${escalation}`,priority,minutes:COST.remediation,meta:{...c,escalation,source}}})}
 unitReviewTasks(){const out=[];for(let id=1;id<=50;id++){const u=this.learning.getUnit(id);if(!u?.accessible||!u.attempts)continue;const mem=memoryEstimate(u,this.clock()),weak=(u.composite||0)<72;if(!u.reviewDue&&!weak)continue;const weakest=Object.entries(u.dimensions||{}).sort((a,b)=>(a[1].effective??100)-(b[1].effective??100))[0]?.[0]||'recognition';const priority=(u.reviewDue?78:55)+mem.risk*22+Math.max(0,75-(u.composite||0))*.35;out.push({id:`unit.${id}`,kind:'unit-review',domain:id>=38&&id<=44?'syntax':id>=45?'reading':'morphology',view:viewForUnit(id),unitId:id,title:`Review Unit ${id} · ${u.title}`,reason:`${u.reviewDue?'Review due':'Weak evidence'} · ${weakest} is weakest · retrieval-risk heuristic ${Math.round(mem.risk*100)}%`,priority,minutes:COST['unit-review'],meta:{memory:mem,weakest,status:u.status}})}return out}
 vocabularyTasks(){if(!this.vocab?.due)return[];const now=this.clock();return this.vocab.due().slice(0,18).map(card=>{const overdue=Math.max(0,days(card.dueAt,now)),leech=card.leech?12:0,relearn=['learning','relearning'].includes(card.state)?5:0,priority=Math.min(105,72+Math.min(12,overdue*2)+(card.lapses||0)*2.5+leech+relearn);return{id:`vocab.${card.id}`,kind:'vocabulary',domain:'vocabulary',view:'vocab',unitId:card.unitId,title:`Recall ${card.front}`,reason:`${card.state}${card.leech?' · leech':''}${card.lapses?` · ${card.lapses} lapse${card.lapses===1?'':'s'}`:''}`,priority,minutes:COST.vocabulary,meta:{cardId:card.id,lemma:card.lemma,lapses:card.lapses||0,leech:!!card.leech,dueAt:card.dueAt}}})}
 morphologyTasks(){if(!this.morph?.stats)return[];const s=this.morph.stats(),out=[];for(const [family,r] of Object.entries(s.byFamily||{})){if((r.attempts||0)<2)continue;const acc=r.correct/r.attempts;if(acc>=.84)continue;const related=this.learning.snapshot().errors||{},errorWeight=Object.values(related).reduce((n,e)=>n+Object.values(e.units||{}).reduce((a,b)=>a+b,0),0);out.push({id:`morph.${family}`,kind:'morphology',domain:'morphology',view:'drill',unitId:null,title:`Practice ${family.replaceAll('-',' ')}`,reason:`Family accuracy ${Math.round(acc*100)}% across ${r.attempts} attempts`,priority:58+(1-acc)*28+Math.min(4,errorWeight*.02),minutes:COST.morphology,meta:{family,accuracy:acc}})}return out.sort((a,b)=>b.priority-a.priority).slice(0,5)}
 syntaxTasks(){if(!this.syntax?.stats)return[];const s=this.syntax.stats(),out=[];for(const [id,r] of Object.entries(s.units||{})){if(!(r.attempts>0)||r.accuracy==null||r.accuracy>=84)continue;const u=this.learning.getUnit(Number(id));out.push({id:`syntax.${id}`,kind:'syntax',domain:'syntax',view:'syntax',unitId:Number(id),title:`Revisit Unit ${id} syntax`,reason:`Syntax accuracy ${r.accuracy}% across ${r.attempts} attempts`,priority:60+(100-r.accuracy)*.32+(u?.reviewDue?8:0),minutes:COST.syntax,meta:{accuracy:r.accuracy}})}return out}
 readingTasks(){const out=[];for(let id=16;id<=50;id++){const u=this.learning.getUnit(id);if(!u?.accessible)continue;const d=u.dimensions?.reading;if(!d?.evidence)continue;const deficit=Math.max(0,(d.threshold||75)-(d.effective||0));if(deficit<8&&!u.reviewDue)continue;out.push({id:`read.${id}`,kind:'reading',domain:'reading',view:id>=45?'fluency':'read',unitId:id,title:`Read for transfer · Unit ${id}`,reason:`Reading transfer ${d.effective}%${u.reviewDue?' · review due':''}`,priority:52+deficit*.45+(u.reviewDue?8:0),minutes:COST.reading,meta:{reading:d.effective}})}return out.slice(0,4)}
 backlog(){const tasks=[...this.remediationTasks(),...this.vocabularyTasks(),...this.unitReviewTasks(),...this.morphologyTasks(),...this.syntaxTasks(),...this.readingTasks()];const seen=new Set();return tasks.filter(t=>{if(seen.has(t.id))return false;seen.add(t.id);return true}).sort((a,b)=>b.priority-a.priority||a.id.localeCompare(b.id))}
 plan({minutes=this.state.settings.dailyMinutes,maxTasks=this.state.settings.maxTasks}={}){minutes=Math.max(5,Number(minutes)||DEFAULT_MINUTES);const pool=this.backlog(),chosen=[],counts={};let remaining=minutes;while(pool.length&&chosen.length<maxTasks){let best=-1,bestScore=-Infinity;for(let i=0;i<pool.length;i++){const t=pool[i];if(t.minutes>remaining+.15&&chosen.length)continue;const count=counts[t.domain]||0,last=chosen.at(-1);let score=t.priority-count*7-(last?.domain===t.domain?9:0);if(t.kind==='remediation'&&chosen.length<2)score+=7;if(score>bestScore){bestScore=score;best=i}}if(best<0)break;const [task]=pool.splice(best,1);chosen.push(task);counts[task.domain]=(counts[task.domain]||0)+1;remaining-=task.minutes;if(remaining<=.2)break}return{generatedAt:iso(this.clock()),budgetMinutes:minutes,estimatedMinutes:Math.round((minutes-Math.max(0,remaining))*10)/10,remainingMinutes:Math.max(0,Math.round(remaining*10)/10),tasks:chosen,backlogCount:this.backlog().length,domains:counts}}
 recommendedNext(){const p=this.plan();if(p.tasks.length)return p.tasks[0];const d=this.learning.getDashboard?.(),r=d?.recommendation;if(r)return{id:`learn.${r.unitId}`,kind:'new-learning',domain:'learning',view:learningViewForUnit(r.unitId),unitId:r.unitId,title:r.title,reason:r.reason,priority:10,minutes:0,meta:{}};return null}
 startSession(minutes=this.state.settings.dailyMinutes){const p=this.plan({minutes});this.state.activeSession={id:`review.${Date.now()}`,startedAt:iso(this.clock()),budgetMinutes:p.budgetMinutes,taskIds:p.tasks.map(t=>t.id),visited:[],finishedAt:null};this.persist();return{...p,sessionId:this.state.activeSession.id}}
 markVisited(taskId){const s=this.state.activeSession;if(!s)return false;if(!s.visited.includes(taskId))s.visited.push(taskId);this.persist();return true}
 finishSession(){const s=this.state.activeSession;if(!s)return null;s.finishedAt=iso(this.clock());const result=clone(s);this.state.history.unshift(result);this.state.history=this.state.history.slice(0,MAX_HISTORY);this.state.activeSession=null;this.persist();return result}
 dashboard(){const p=this.plan(),clusters=this.errorClusters(),vocab=this.vocab?.stats?.()||null;return{plan:p,recommendation:this.recommendedNext(),clusters:clusters.slice(0,6),dueVocabulary:vocab?.due||0,leeches:vocab?.leeches||0,activeSession:clone(this.state.activeSession),settings:clone(this.state.settings)}}
}
return{STORAGE_KEY,SCHEMA,DEFAULT_MINUTES,COST,MemoryStorage,domainForSource,viewForUnit,learningViewForUnit,memoryEstimate,AdaptiveReviewEngine};
});