(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.KoineAITutor=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const STORAGE_KEY='koine-path-ai-tutor-v1';
const MAX_HISTORY=8,MAX_MESSAGE=2000,MAX_EVIDENCE=24,MAX_EVIDENCE_TEXT=900;
const MODES=['socratic','explain','translation-feedback'];
function safe(raw,fallback){try{return raw?JSON.parse(raw):fallback}catch{return fallback}}
function clip(v,n){return String(v??'').slice(0,n)}
function cleanEvidence(e,i){return{id:clip(e?.id||`e${i+1}`,96),kind:clip(e?.kind||'context',40),authority:clip(e?.authority||'reviewed',32),content:clip(e?.content||'',MAX_EVIDENCE_TEXT)}}
function makeClientId(storage){let id=storage?.getItem?.('koine-path-ai-client-id');if(!id){id=(globalThis.crypto?.randomUUID?.()||`kp-${Date.now()}-${Math.random().toString(36).slice(2)}`);storage?.setItem?.('koine-path-ai-client-id',id)}return id}
function responseValid(x){return!!x&&typeof x.answer==='string'&&['grounded','mixed','uncertain'].includes(x.confidence)&&Array.isArray(x.evidence_ids)&&Array.isArray(x.follow_up)&&typeof x.boundary_note==='string'}
function fallback(message,context={}){const q=String(message).toLowerCase(),reader=context.reader||null,syntax=context.syntax||null;let answer='Start with one observable Greek feature: identify the finite verb, then its subject and complements. If a nonfinite form is present, ask what finite predication it depends on.';if(syntax?.prompt)answer=`Use the reviewed structure already attached to ${syntax.reference}. First answer this narrower question: ${syntax.prompt}`;else if(reader?.selected?.parse)answer=`For ${reader.selected.form}, begin with the form rather than an English gloss. Which part of the parse can you identify independently before revealing more?`;else if(q.includes('dative'))answer='Identify whether a preposition governs the dative before assigning a semantic case label. Case form is morphological; labels such as means, location, or cause require the construction and context.';else if(q.includes('aorist'))answer='Identify the aorist form first. Do not reduce aorist to “once” or “simple past”; tense-form and contextual discourse contribution are separate questions.';else if(q.includes('translate'))answer='Draft structurally first: preserve the main finite predication and subordinate relationships, then revise the English for naturalness. Do not force one English word onto every occurrence of a lemma.';return{answer,confidence:'grounded',evidence_ids:[],follow_up:['What Greek form or clause relationship can you identify without another reveal?'],boundary_note:'Local deterministic fallback. No model request was made.',disputed:false}}
class AITutor{
 constructor({endpoint='',storage=null,fetchFn=null,contextProvider=null,timeoutMs=20000}={}){this.storage=storage||((typeof localStorage!=='undefined')?localStorage:null);this.endpoint=endpoint;this.fetchFn=fetchFn||((typeof fetch!=='undefined')?fetch.bind(globalThis):null);this.contextProvider=contextProvider||(()=>({}));this.timeoutMs=timeoutMs;this.state=safe(this.storage?.getItem?.(STORAGE_KEY),{history:[]});this.state.history=Array.isArray(this.state.history)?this.state.history.slice(-MAX_HISTORY):[];this.clientId=makeClientId(this.storage)}
 persist(){this.storage?.setItem?.(STORAGE_KEY,JSON.stringify({history:this.state.history.slice(-MAX_HISTORY)}))}
 clear(){this.state.history=[];this.persist()}
 history(){return this.state.history.slice()}
 context(){const c=this.contextProvider?.()||{};return sanitizeContext(c)}
 async ask(message,{mode='socratic',includeContext=true}={}){message=clip(message,MAX_MESSAGE).trim();if(!message)throw new Error('Enter a question first.');if(!MODES.includes(mode))mode='socratic';const context=includeContext?this.context():{};const payload={version:1,clientId:this.clientId,mode,message,history:this.state.history.slice(-MAX_HISTORY).map(x=>({role:x.role==='assistant'?'assistant':'user',content:clip(x.content,1600)})),context};let result=null,remote=false;
   if(this.endpoint&&this.fetchFn){const controller=typeof AbortController!=='undefined'?new AbortController():null,timer=controller?setTimeout(()=>controller.abort(),this.timeoutMs):null;try{const r=await this.fetchFn(this.endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller?.signal});if(!r.ok)throw new Error(`Tutor service returned ${r.status}`);const json=await r.json();if(!responseValid(json))throw new Error('Tutor response schema was invalid');result=json;remote=true}catch(err){result=fallback(message,context);result.boundary_note=`Secure tutor unavailable (${err.name==='AbortError'?'timeout':'service error'}). ${result.boundary_note}`}finally{if(timer)clearTimeout(timer)}}else result=fallback(message,context);
   this.state.history.push({role:'user',content:message},{role:'assistant',content:result.answer,meta:{confidence:result.confidence,remote}});this.state.history=this.state.history.slice(-MAX_HISTORY);this.persist();return{...result,remote,context};
 }
}
function sanitizeContext(c={}){const evidence=[];(Array.isArray(c.evidence)?c.evidence:[]).slice(0,MAX_EVIDENCE).forEach((e,i)=>evidence.push(cleanEvidence(e,i)));return{curriculum:c.curriculum?{unitId:Number(c.curriculum.unitId)||null,unitTitle:clip(c.curriculum.unitTitle,160),stageId:clip(c.curriculum.stageId,16)}:null,reader:c.reader?{reference:clip(c.reader.reference,80),passage:clip(c.reader.passage,2500),assistance:clip(c.reader.assistance,8),selected:c.reader.selected?{id:clip(c.reader.selected.id,120),form:clip(c.reader.selected.form,120),lemma:clip(c.reader.selected.lemma,120),parse:clip(c.reader.selected.parse,300),sourceParse:clip(c.reader.selected.sourceParse,32)}:null}:null,syntax:c.syntax?{exerciseId:clip(c.syntax.exerciseId,120),unitId:Number(c.syntax.unitId)||null,reference:clip(c.syntax.reference,80),prompt:clip(c.syntax.prompt,500),reviewedAnswer:clip(c.syntax.reviewedAnswer,500),explanation:clip(c.syntax.explanation,900),structure:(Array.isArray(c.syntax.structure)?c.syntax.structure:[]).slice(0,12).map(x=>clip(x,220)),draft:clip(c.syntax.draft,2200),ambiguous:!!c.syntax.ambiguous}:null,evidence};}
return{AITutor,sanitizeContext,fallback,responseValid,STORAGE_KEY,MODES};
});