(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.KoineExegesis=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const STORAGE_KEY='koine-path-exegesis-lab-v1',SCHEMA=1,MAX_HISTORY=240,HELP={none:0,hint:1,constraint:2,full:3};
const clone=v=>JSON.parse(JSON.stringify(v));const safe=s=>{try{return JSON.parse(s)}catch{return null}};const iso=d=>new Date(d).toISOString();const norm=s=>String(s||'').normalize('NFC');
class MemoryStorage{constructor(seed={}){this.m=new Map(Object.entries(seed))}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.m.set(k,String(v))}}
function initial(now){return{schemaVersion:SCHEMA,selectedCaseId:null,cases:{},notes:{},history:[],createdAt:iso(now),updatedAt:iso(now)}}
function blankCase(){return{attempts:0,correct:0,lastAt:null,assistLevel:'none',completed:false}}
function refLabel(r){return `${r.book} ${r.chapter}:${r.startVerse}${r.endVerse!==r.startVerse?`–${r.endVerse}`:''}`}
function bg3Hint(level){return level==='constraint'?'lemma':level==='full'?'full':level==='hint'?'hint':'none'}
class ExegesisEngine{
 constructor({data,learningEngine=null,vocabularyEngine=null,storage=null,clock=()=>new Date(),fetchFn=null,basePath='generated/corpus/books',lexicalIndexPath='generated/corpus/lexical-index.json'}={}){if(!data?.cases)throw new Error('ExegesisEngine requires reviewed BG11 data.');this.data=data;this.learning=learningEngine;this.vocab=vocabularyEngine;this.storage=storage||((typeof localStorage!=='undefined')?localStorage:new MemoryStorage());this.clock=clock;this.fetchFn=fetchFn||((typeof fetch!=='undefined')?fetch.bind(globalThis):null);this.basePath=basePath;this.lexicalIndexPath=lexicalIndexPath;this.bookCache=new Map();this.lexicalIndex=null;this.lexicalMap=null;const saved=safe(this.storage.getItem(STORAGE_KEY));this.state={...initial(clock()),...(saved||{})};this.state.cases=this.state.cases||{};this.state.notes=this.state.notes||{};this.state.history=Array.isArray(this.state.history)?this.state.history:[];this.persist()}
 persist(){this.state.updatedAt=iso(this.clock());this.storage.setItem(STORAGE_KEY,JSON.stringify(this.state))}snapshot(){return clone(this.state)}caseDef(id){return this.data.cases.find(x=>x.id===id)||null}caseState(id){return{...blankCase(),...(this.state.cases[id]||{})}}
 async loadBook(id){if(this.bookCache.has(id))return this.bookCache.get(id);if(!this.fetchFn)throw new Error('Corpus fetch unavailable');const r=await this.fetchFn(`${this.basePath}/${encodeURIComponent(id)}.json`,{cache:'force-cache'});if(!r.ok)throw new Error(`${id}: HTTP ${r.status}`);const b=await r.json();this.bookCache.set(id,b);return b}
 async materialize(id){const def=typeof id==='string'?this.caseDef(id):id;if(!def)throw new Error('Unknown exegesis case');const book=await this.loadBook(def.ref.book),chapter=book.chapters?.[String(def.ref.chapter)];if(!chapter)throw new Error(`Missing chapter ${def.ref.book}.${def.ref.chapter}`);const verses=[];for(let v=def.ref.startVerse;v<=def.ref.endVerse;v++)if(chapter[String(v)])verses.push({verse:v,tokens:chapter[String(v)]});const tokens=verses.flatMap(v=>v.tokens);if(!tokens.length)throw new Error(`Empty exegesis passage ${def.id}`);return{...clone(def),reference:`${book.book.name||def.ref.book} ${def.ref.chapter}:${def.ref.startVerse}${def.ref.endVerse!==def.ref.startVerse?`–${def.ref.endVerse}`:''}`,verses,tokens,text:tokens.map(t=>t.text).join(' ')}}
 setSelected(id){if(!this.caseDef(id))throw new Error('Unknown exegesis case');this.state.selectedCaseId=id;this.state.cases[id]??=blankCase();this.persist()}
 useHelp(id,level){if(!(level in HELP)||level==='none')return null;const def=this.caseDef(id);if(!def)throw new Error('Unknown exegesis case');const rec=this.state.cases[id]??=blankCase();if(HELP[level]>HELP[rec.assistLevel||'none'])rec.assistLevel=level;rec.lastAt=iso(this.clock());const u=this.learning?.getUnit?.(def.unitId);if(u?.accessible)this.learning.recordHint({unitId:def.unitId,itemId:def.id,level:bg3Hint(level),source:'exegesis-lab'});else this.learning?.recordExposure?.({unitId:def.unitId,itemId:def.id,source:'exegesis-help'});this.persist();return level==='hint'?def.hint:level==='constraint'?def.constraint:def.ladder}
 answer(id,index){const def=this.caseDef(id);if(!def)throw new Error('Unknown exegesis case');const rec=this.state.cases[id]??=blankCase(),correct=Number(index)===Number(def.answer),help=rec.assistLevel||'none';rec.attempts++;if(correct)rec.correct++;rec.completed=rec.completed||correct;rec.lastAt=iso(this.clock());this.state.history.unshift({caseId:id,unitId:def.unitId,kind:def.kind,correct,assistLevel:help,at:rec.lastAt});this.state.history=this.state.history.slice(0,MAX_HISTORY);const u=this.learning?.getUnit?.(def.unitId);if(u?.accessible)this.learning.recordEvidence({unitId:def.unitId,dimension:def.dimension,correct,hintLevel:bg3Hint(help),errorType:correct?null:def.errorType,itemId:def.id,source:'exegesis-lab',confidence:.78});else this.learning?.recordExposure?.({unitId:def.unitId,itemId:def.id,source:'exegesis-lab'});this.persist();return{correct,assistLevel:help,ladder:clone(def.ladder)}}
 resetHelp(id){const rec=this.state.cases[id];if(rec){rec.assistLevel='none';this.persist()}}
 saveNote(id,text){if(!this.caseDef(id))throw new Error('Unknown exegesis case');this.state.notes[id]={text:String(text||'').slice(0,8000),updatedAt:iso(this.clock())};this.persist();return clone(this.state.notes[id])}
 note(id){return clone(this.state.notes[id]||{text:'',updatedAt:null})}
 stats(){const records=this.data.cases.map(c=>({def:c,state:this.caseState(c.id)})),attempted=records.filter(x=>x.state.attempts),correct=attempted.reduce((s,x)=>s+x.state.correct,0),attempts=attempted.reduce((s,x)=>s+x.state.attempts,0),byUnit={};for(const x of records){const r=byUnit[x.def.unitId]??={attempts:0,correct:0,completed:0,total:0};r.total++;r.attempts+=x.state.attempts;r.correct+=x.state.correct;if(x.state.completed)r.completed++}return{cases:this.data.cases.length,attempts,correct,accuracy:attempts?Math.round(correct/attempts*100):null,completed:records.filter(x=>x.state.completed).length,byUnit}}
 recommendedCase(unitId=null){let pool=this.data.cases.filter(c=>!unitId||c.unitId===Number(unitId));if(!pool.length)return null;const score=c=>{const r=this.caseState(c.id),u=this.learning?.getUnit?.(c.unitId),locked=u&&!u.accessible;return (r.completed?0:70)+(r.attempts?Math.max(0,30-r.correct/Math.max(1,r.attempts)*30):25)+(u?.reviewDue?12:0)-(locked?20:0)-r.attempts*2};return clone(pool.sort((a,b)=>score(b)-score(a)||a.id.localeCompare(b.id))[0])}
 async loadLexicalIndex(){if(this.lexicalIndex)return this.lexicalIndex;if(!this.fetchFn)throw new Error('Lexical index fetch unavailable');const r=await this.fetchFn(this.lexicalIndexPath,{cache:'force-cache'});if(!r.ok)throw new Error(`lexical-index: HTTP ${r.status}`);const data=await r.json();if(!Array.isArray(data.entries)||!data.sourceRevision)throw new Error('Malformed lexical index');this.lexicalIndex=data;this.lexicalMap=new Map(data.entries.map(x=>[norm(x.lemma),x]));return data}
 async lemmaProfile(lemma){await this.loadLexicalIndex();lemma=norm(lemma);const entry=this.lexicalMap.get(lemma);if(!entry)return null;const vocab=this.vocab?.entry?.(lemma)||null;return{...clone(entry),referenceGloss:vocab?.referenceGloss||null,glossSource:vocab?.source||null,indexNote:this.lexicalIndex.note}}
 async sampleContexts(lemma,limit=6){const p=await this.lemmaProfile(lemma);if(!p)return[];const out=[];for(const ref of p.sampleRefs.slice(0,Math.max(1,limit))){const [bookId,c,v]=ref.split('.');try{const book=await this.loadBook(bookId),tokens=book.chapters?.[String(c)]?.[String(v)]||[];out.push({ref,text:tokens.map(t=>t.text).join(' '),tokens:clone(tokens)})}catch{}}return out}
 method(){return clone(this.data.method)}
}
return{STORAGE_KEY,SCHEMA,HELP,MemoryStorage,refLabel,bg3Hint,ExegesisEngine};
});