(()=>{
'use strict';
const data=window.KOINE_EXEGESIS_DATA,api=window.KoineExegesis,learning=window.KOINE_LEARNING_ENGINE;if(!data||!api||!learning)return;
const vocab=window.KOINE_VOCAB_ENGINE||null,engine=new api.ExegesisEngine({data,learningEngine:learning,vocabularyEngine:vocab});window.KOINE_EXEGESIS_ENGINE=engine;
if(typeof titles!=='undefined')titles.exegesis=['Exegesis','Observe carefully. Argue only as far as the evidence allows.'];
const nav=document.querySelector('.nav'),anchor=nav?.querySelector('[data-view="fluency"]')||nav?.querySelector('[data-view="read"]');if(nav&&!nav.querySelector('[data-view="exegesis"]')){const b=document.createElement('button');b.dataset.view='exegesis';b.textContent='Exegesis';anchor?.after(b);b.addEventListener('click',()=>openView('exegesis'));}
const main=document.querySelector('.content'),tutor=document.querySelector('#tutor'),section=document.createElement('section');section.id='exegesis';section.className='view';main?.insertBefore(section,tutor||null);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const kindLabel=s=>String(s||'').replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase());
let activeTab='cases',activeFilter='all',material=null;
function unitName(id){return id===48?'Lexicon & word study':id===49?'Edition & tool awareness':'Integrated exegesis';}
function stats(){const s=engine.stats(),u=id=>s.byUnit[id]||{completed:0,total:0};return `<div class="exegesis-metrics"><div><span>Reviewed cases</span><strong>${s.cases}</strong></div><div><span>Completed</span><strong>${s.completed}</strong></div><div><span>Accuracy</span><strong>${s.accuracy==null?'—':s.accuracy+'%'}</strong></div><div><span>Stage 7 cases</span><strong>${u(48).completed+u(49).completed+u(50).completed}/${u(48).total+u(49).total+u(50).total}</strong></div></div>`;}
function tabButtons(){return `<div class="exegesis-tabs"><button class="btn" data-ex-tab="cases" aria-pressed="${activeTab==='cases'}">Case laboratory</button><button class="btn" data-ex-tab="lexical" aria-pressed="${activeTab==='lexical'}">Corpus word study</button><button class="btn" data-ex-tab="method" aria-pressed="${activeTab==='method'}">Method ladder</button></div>`;}
function wireTabs(){section.querySelectorAll('[data-ex-tab]').forEach(b=>b.addEventListener('click',()=>{activeTab=b.dataset.exTab;renderHome()}));}
function renderHome(){section.innerHTML=`<div class="eyebrow">Intermediate & exegetical Greek · BG11</div><h1>Know what the Greek can—and cannot—establish.</h1><p class="lede">Advanced reading now moves beyond parsing into lexical method, verbal aspect, discourse, edition awareness, argument tracing, and explicit evidence boundaries.</p>${stats()}${tabButtons()}<div id="exegesis-body"></div>`;wireTabs();if(activeTab==='lexical')renderLexical();else if(activeTab==='method')renderMethod();else renderCases();}
function renderCases(){const host=section.querySelector('#exegesis-body'),rec=engine.recommendedCase(),filtered=data.cases.filter(c=>activeFilter==='all'||String(c.unitId)===activeFilter);host.innerHTML=`<div class="exegesis-layout"><article><div class="section-head"><div><h2>Reviewed case laboratory</h2><p>Correct answers can contribute BG3 evidence only when the mapped Stage 7 unit is accessible.</p></div></div><div class="exegesis-filter"><button class="btn" data-unit-filter="all">All</button><button class="btn" data-unit-filter="48">Unit 48</button><button class="btn" data-unit-filter="49">Unit 49</button><button class="btn" data-unit-filter="50">Unit 50</button></div><div class="exegesis-case-list">${filtered.map(c=>{const s=engine.caseState(c.id),u=learning.getUnit(c.unitId);return `<div class="exegesis-case-row"><span class="case-unit">U${c.unitId}</span><div><h3>${esc(kindLabel(c.kind))} · ${esc(c.ref.book)} ${c.ref.chapter}:${c.ref.startVerse}${c.ref.endVerse!==c.ref.startVerse?'–'+c.ref.endVerse:''}</h3><p>${esc(c.question)}</p><span class="case-status ${s.completed?'done':''}">${s.completed?'completed':u?.accessible?'available':'preview · unit locked'}</span></div><button class="btn" data-open-case="${esc(c.id)}">Open</button></div>`}).join('')}</div></article><aside class="panel"><div class="eyebrow">Recommended case</div>${rec?`<h3>${kindLabel(rec.kind)}</h3><p>${esc(rec.question)}</p><small>Unit ${rec.unitId} · ${unitName(rec.unitId)}</small><div class="exegesis-actions"><button class="btn primary" data-open-case="${esc(rec.id)}">Start case</button></div>`:'<p>No reviewed case available.</p>'}<div class="fluency-rule"></div><div class="eyebrow">Reasoning boundary</div><p>BG11 never turns a morphology tag, gloss, corpus count, apparatus line, or AI answer directly into theology.</p></aside></div>`;host.querySelectorAll('[data-unit-filter]').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.unitFilter;renderCases()}));host.querySelectorAll('[data-open-case]').forEach(b=>b.addEventListener('click',()=>openCase(b.dataset.openCase)));}
async function openCase(id){engine.setSelected(id);section.innerHTML='<div class="eyebrow">BG11 case laboratory</div><h1>Loading canonical passage…</h1>';try{material=await engine.materialize(id)}catch(e){section.innerHTML=`<div class="eyebrow">BG11 case laboratory</div><h1>Corpus unavailable.</h1><p>${esc(e.message)}</p><button class="btn" id="ex-back">Back</button>`;section.querySelector('#ex-back').onclick=renderHome;return}renderCase();}
function renderCase(){const c=material,s=engine.caseState(c.id),u=learning.getUnit(c.unitId),note=engine.note(c.id);section.innerHTML=`<button class="btn text" id="ex-back">← Exegesis cases</button><div class="eyebrow">Unit ${c.unitId} · ${esc(kindLabel(c.kind))} · ${esc(c.reference)}</div><h1>${esc(unitName(c.unitId))}</h1><div class="exegesis-layout"><article><div class="exegesis-passage">${esc(c.text)}</div>${c.variant?`<div class="apparatus-note"><strong>Edition-comparison flag:</strong> ${esc(c.variant.summary)}<br><small>Pinned Faithlife/SBLGNT apparatus ${esc(c.variant.sourceRevision.slice(0,10))}. This is not manuscript evidence.</small></div>`:''}<div class="exegesis-question">${esc(c.question)}</div><div class="exegesis-options">${c.choices.map((x,i)=>`<button data-ex-answer="${i}">${esc(x)}</button>`).join('')}</div><div id="ex-feedback"></div><div class="exegesis-actions"><button class="btn" data-ex-help="hint">Observation hint</button><button class="btn" data-ex-help="constraint">Constraint</button><button class="btn" data-ex-help="full">Reviewed analysis</button></div><div id="ex-help" class="exegesis-help" hidden></div><div id="ex-ladder"></div></article><aside><div class="panel"><div class="eyebrow">Evidence status</div><h3>${u?.accessible?'Canonical evidence enabled':'Preview mode'}</h3><p>${u?.accessible?'A scored answer writes assisted/unassisted evidence into BG3.':'This unit is not yet accessible. Practice is recorded only as exposure.'}</p><small>${s.attempts} attempt${s.attempts===1?'':'s'} · ${s.correct} correct · help level ${esc(s.assistLevel)}</small></div><div class="panel exegesis-note"><div class="eyebrow">Exegetical notebook</div><p>Write observations and arguments. Notes never create mastery.</p><textarea id="ex-note" placeholder="Observation → evidence → inference…">${esc(note.text)}</textarea><button class="btn" id="ex-save-note">Save note</button><small id="ex-note-status">${note.updatedAt?'Saved '+note.updatedAt.slice(0,10):'Local only'}</small></div></aside></div>`;
section.querySelector('#ex-back').onclick=()=>{material=null;renderHome()};section.querySelectorAll('[data-ex-answer]').forEach(b=>b.addEventListener('click',()=>answerCase(Number(b.dataset.exAnswer))));section.querySelectorAll('[data-ex-help]').forEach(b=>b.addEventListener('click',()=>showHelp(b.dataset.exHelp)));section.querySelector('#ex-save-note').onclick=()=>{engine.saveNote(c.id,section.querySelector('#ex-note').value);section.querySelector('#ex-note-status').textContent='Saved locally';};if(s.completed)renderLadder(c.ladder);}
function showHelp(level){const value=engine.useHelp(material.id,level),host=section.querySelector('#ex-help');host.hidden=false;if(level==='full'){host.innerHTML='<strong>Reviewed analysis unlocked.</strong><p>The reasoning ladder below separates observation from inference.</p>';renderLadder(value)}else host.textContent=value;}
function answerCase(index){const result=engine.answer(material.id,index),host=section.querySelector('#ex-feedback');host.className='feedback '+(result.correct?'good':'bad');host.textContent=result.correct?'Correct. The reasoning boundary is now shown.':'Not yet. Compare the grammatical fact with the inference being claimed.';section.querySelectorAll('[data-ex-answer]').forEach(b=>b.disabled=true);renderLadder(result.ladder);window.renderLearningEngineUI?.();window.renderAdaptiveReview?.();}
function renderLadder(l){if(!l)return;const host=section.querySelector('#ex-ladder');if(!host)return;const step=(name,items)=>`<div class="reasoning-step"><strong>${name}</strong><ul>${(items||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`;host.innerHTML=`<div class="reasoning-ladder">${step('Grammatical facts',l.facts)}${step('Contextual judgments',l.judgments)}${step('Interpretive possibilities',l.possibilities)}</div><div class="reasoning-boundary"><strong>Boundary:</strong> ${esc(l.boundary)}</div>`;}
function renderMethod(){const host=section.querySelector('#exegesis-body'),m=engine.method();host.innerHTML=`<div class="exegesis-layout"><article class="panel"><div class="eyebrow">Four-layer reasoning contract</div><div class="reasoning-ladder">${m.ladder.map((x,i)=>`<div class="reasoning-step"><strong>${i+1}. ${esc(x.replaceAll('_',' '))}</strong><span>${['What the text/form directly establishes.','What context and syntax make most plausible.','Readings still defensible after constraints are applied.','Broader synthesis argued from the passage and canon.'][i]}</span></div>`).join('')}</div></article><aside class="panel"><div class="eyebrow">Non-negotiable safeguards</div><ul>${m.rules.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></aside></div>`;}
function renderLexical(){const host=section.querySelector('#exegesis-body');host.innerHTML=`<div class="section-head"><div><h2>Exact-corpus word study</h2><p>Use frequency, distribution, nearby lemmas, sample contexts, and BG5 reference glosses without treating any one signal as a definition.</p></div></div><div class="lexical-search"><input id="lexical-query" value="λόγος" aria-label="Greek lemma"><button class="btn primary" id="lexical-go">Study lemma</button></div><div id="lexical-result"><div class="empty">Enter an exact Greek lemma from the generated MorphGNT corpus.</div></div>`;const go=()=>lookupLemma(section.querySelector('#lexical-query').value.trim());section.querySelector('#lexical-go').onclick=go;section.querySelector('#lexical-query').addEventListener('keydown',e=>{if(e.key==='Enter')go()});}
async function lookupLemma(lemma){const host=section.querySelector('#lexical-result');if(!lemma)return;host.innerHTML='<div class="empty">Loading exact-corpus profile…</div>';try{const [p,contexts]=await Promise.all([engine.lemmaProfile(lemma),engine.sampleContexts(lemma,6)]);if(!p){host.innerHTML='<div class="empty">Lemma not found in the generated NT index. Use the normalized dictionary lemma, including accents where applicable.</div>';return}host.innerHTML=`<div class="lexical-profile"><article class="panel"><div class="eyebrow">Lemma profile</div><h2 class="greek">${esc(p.lemma)}</h2><span class="lexical-meta">Rank #${p.rank} · ${p.count.toLocaleString()} occurrences · ${p.band}</span>${p.referenceGloss?`<p><strong>BG5 reference gloss:</strong> ${esc(p.referenceGloss)}</p>`:'<p>No reviewed/reference gloss loaded.</p>'}<p class="exegesis-caution">Reference glosses are retrieval prompts, not definitions. ${esc(p.indexNote)}</p><h3>Book distribution</h3><table class="lexical-table"><tbody>${p.books.slice(0,10).map(x=>`<tr><td>${esc(x.book)}</td><td>${x.count}</td></tr>`).join('')}</tbody></table></article><aside class="panel"><div class="eyebrow">Nearby lemmas · ±3 tokens</div><div class="lexical-nearby">${p.nearbyLemmas.map(x=>`<span class="greek">${esc(x.lemma)} <small>${x.count}</small></span>`).join('')}</div><p class="exegesis-caution">These are raw co-occurrence counts. They can suggest usage patterns to inspect; they do not establish semantic relationships automatically.</p></aside></div><div class="panel"><div class="section-head"><div><h3>Sample contexts</h3><p>Deterministic sample verse references from the exact pinned corpus.</p></div></div>${contexts.map(x=>`<div class="lexical-context"><strong>${esc(x.ref)}</strong><span class="greek">${esc(x.text)}</span></div>`).join('')}</div>`;}catch(e){host.innerHTML=`<div class="empty">Lexical index unavailable: ${esc(e.message)}. It is generated during the Pages/full-corpus build.</div>`;}}
window.renderExegesisLab=renderHome;renderHome();
})();