(function(){
'use strict';
const engine=window.KOINE_GUIDANCE_ENGINE;if(!engine)return;
let screen='welcome';
const labels={
  experience:{new:'New to Biblical Greek',alphabet:'I know the alphabet / basics',coursework:'I have taken a Greek course','returning-reader':'I have read Greek before'},
  goal:{'read-nt':'Read the Greek New Testament','course-mastery':'Work through the full course','grammar-refresh':'Refresh grammar and morphology',exegesis:'Build toward responsible exegesis'}
};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function host(id){return document.getElementById(id)}
function ensureDialog(){let d=host('guidance-dialog');if(d)return d;d=document.createElement('dialog');d.id='guidance-dialog';d.className='guidance-dialog';d.setAttribute('aria-labelledby','guidance-dialog-title');d.addEventListener('close',()=>{renderPlan();renderSettings()});document.body.appendChild(d);return d}
function openDialog(next='welcome'){screen=next;const d=ensureDialog();renderDialog();if(!d.open)d.showModal()}
function closeDialog(){const d=ensureDialog();if(d.open)d.close()}
function profileForm(){const p=engine.snapshot().profile;return `<div class="guidance-step"><div class="eyebrow">Step 1 of 2</div><h2 id="guidance-dialog-title">Build your study path</h2><p>These choices shape session recommendations. They never alter mastery evidence.</p><label>Previous Greek experience<select id="guide-experience">${Object.entries(labels.experience).map(([v,l])=>`<option value="${v}" ${p.experience===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Main goal<select id="guide-goal">${Object.entries(labels.goal).map(([v,l])=>`<option value="${v}" ${p.goal===v?'selected':''}>${l}</option>`).join('')}</select></label><fieldset><legend>Typical session</legend><div class="guidance-choice-row">${[10,25,45].map(n=>`<label class="guidance-choice"><input type="radio" name="guide-minutes" value="${n}" ${p.sessionMinutes===n?'checked':''}><span>${n} min</span></label>`).join('')}</div></fieldset><label>Study days per week<select id="guide-days">${[3,4,5,6,7].map(n=>`<option value="${n}" ${p.daysPerWeek===n?'selected':''}>${n} days</option>`).join('')}</select></label><div class="guidance-actions"><button class="btn" data-guide-action="close">Cancel</button><button class="btn primary" data-guide-action="save-profile">Continue</button></div></div>`}
function welcome(){return `<div class="guidance-step"><div class="eyebrow">Koinē Path v1.3</div><h2 id="guidance-dialog-title">Start at the right pace.</h2><p>Koinē Path can build a daily route around your goal, available time, existing mastery evidence, and an optional 16-question placement diagnostic.</p><div class="guidance-note"><strong>Placement never grants mastery.</strong><span>It only changes routing. Course unlocks still require the canonical evidence system.</span></div><div class="guidance-actions"><button class="btn" data-guide-action="skip-all">Use defaults</button><button class="btn primary" data-guide-action="profile">Set up my path</button></div></div>`}
function placementIntro(){return `<div class="guidance-step"><div class="eyebrow">Step 2 of 2</div><h2 id="guidance-dialog-title">Calibrate with placement?</h2><p>The diagnostic samples script, morphology, syntax, reading method, and exegetical safeguards across all eight stages.</p><div class="guidance-note"><strong>16 questions · provisional result</strong><span>A high result creates an accelerated validation route through earlier canonical units; it does not skip their mastery checks.</span></div><div class="guidance-actions"><button class="btn" data-guide-action="skip-placement">Skip placement</button><button class="btn primary" data-guide-action="start-placement">Start diagnostic</button></div></div>`}
function placementQuestion(){const questions=engine.questions(),answered=engine.snapshot().placement.answers||{},done=Object.keys(answered).length;if(done===questions.length)return finishPlacement();const idx=questions.findIndex(q=>answered[q.id]===undefined),q=questions[Math.max(0,idx)];return `<div class="guidance-step"><div class="guidance-progress"><span>Placement ${done+1} / ${questions.length}</span><progress max="${questions.length}" value="${done}"></progress></div><h2 id="guidance-dialog-title">${esc(q.prompt)}</h2><div class="guidance-options">${q.options.map((o,i)=>`<button class="guidance-option" data-guide-answer="${i}" data-question-id="${q.id}">${esc(o)}</button>`).join('')}</div><p class="guidance-footnote">Your answer is stored only in the local guidance profile. It cannot write canonical mastery evidence.</p><div class="guidance-actions"><button class="btn" data-guide-action="close">Finish later</button></div></div>`}
function finishPlacement(){return resultMarkup(engine.completePlacement())}
function resultMarkup(result){return `<div class="guidance-step"><div class="eyebrow">Placement result</div><h2 id="guidance-dialog-title">Provisional level: ${esc(result.stageId)} · ${esc(result.stageTitle)}</h2><p><strong>${result.score} / ${result.total}</strong> diagnostic items correct.</p><p>${esc(result.outcome)}</p><div class="guidance-stage-grid">${result.byStage.map(s=>`<div><span>${esc(s.id)}</span><strong>${s.correct}/${s.total}</strong><small>${esc(s.title)}</small></div>`).join('')}</div><div class="guidance-note"><strong>No course content was unlocked.</strong><span>${esc(result.notice)}</span></div><div class="guidance-actions"><button class="btn" data-guide-action="retake">Retake</button><button class="btn primary" data-guide-action="finish">Use this study path</button></div></div>`}
function renderDialog(){const d=ensureDialog(),result=engine.getPlacementResult();if(screen==='profile')d.innerHTML=profileForm();else if(screen==='placement-intro')d.innerHTML=placementIntro();else if(screen==='placement')d.innerHTML=placementQuestion();else if(screen==='result'&&result)d.innerHTML=resultMarkup(result);else d.innerHTML=welcome();bindDialog(d)}
function bindDialog(d){d.querySelectorAll('[data-guide-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.guideAction;if(a==='close')return closeDialog();if(a==='profile'){screen='profile';return renderDialog()}if(a==='save-profile'){const minutes=Number(d.querySelector('input[name="guide-minutes"]:checked')?.value||25);engine.saveProfile({experience:d.querySelector('#guide-experience').value,goal:d.querySelector('#guide-goal').value,sessionMinutes:minutes,daysPerWeek:Number(d.querySelector('#guide-days').value)});screen='placement-intro';return renderDialog()}if(a==='skip-all'){engine.saveProfile({experience:'new',goal:'read-nt',sessionMinutes:25,daysPerWeek:5});engine.skipPlacement();engine.finishOnboarding({skipped:true});closeDialog();return renderAll()}if(a==='skip-placement'){engine.skipPlacement();engine.finishOnboarding();closeDialog();return renderAll()}if(a==='start-placement'||a==='retake'){engine.startPlacement();screen='placement';return renderDialog()}if(a==='finish'){engine.finishOnboarding();closeDialog();return renderAll()}}));d.querySelectorAll('[data-guide-answer]').forEach(b=>b.addEventListener('click',()=>{engine.answerPlacement(b.dataset.questionId,Number(b.dataset.guideAnswer));screen=engine.placementProgress().complete?'result':'placement';renderDialog()}))}
function go(task){if(task.view==='setup')return openDialog('welcome');window.KOINE_APP_OPEN_VIEW?.(task.view);if(task.view==='learn'&&task.unitId)window.KOINE_COURSE_UI?.openUnit?.(task.unitId)}
function renderPlan(){const el=host('guided-plan');if(!el)return;const plan=engine.getGuidedPlan();el.innerHTML=`<div class="section-head"><div><h2>${esc(plan.title)}</h2><p>${esc(plan.summary)}</p></div>${plan.status==='ready'?`<span class="guidance-budget">${plan.minutes} min</span>`:''}</div><div class="guided-plan-grid">${plan.tasks.map((t,i)=>`<article class="panel guided-task ${i===0?'guided-task-primary':''}"><div><small>${i===0?'Next':'Then'} · ${t.minutes} min</small><strong>${esc(t.title)}</strong>${t.reason?`<span>${esc(t.reason)}</span>`:''}</div><button class="btn ${i===0?'primary':''}" data-guide-task="${i}">${t.view==='setup'?'Set up':'Open'}</button></article>`).join('')}</div>`;el.querySelectorAll('[data-guide-task]').forEach(b=>b.addEventListener('click',()=>go(plan.tasks[Number(b.dataset.guideTask)])))}
function renderSettings(){const el=host('study-path-settings');if(!el)return;const s=engine.snapshot(),r=engine.getPlacementResult();el.innerHTML=`<div class="panel guidance-settings"><div><div class="eyebrow">Guided study</div><h3>${esc(labels.goal[s.profile.goal])}</h3><p>${esc(labels.experience[s.profile.experience])} · ${s.profile.sessionMinutes} min/session · ${s.profile.daysPerWeek} days/week</p>${r?`<p>Placement: <strong>${r.stageId} · ${esc(r.stageTitle)}</strong> (${r.score}/${r.total})</p>`:'<p>Placement: not used.</p>'}</div><div class="guidance-actions"><button class="btn" id="edit-guidance">Edit setup</button><button class="btn" id="retake-guidance">${r?'Retake placement':'Take placement'}</button></div></div>`;host('edit-guidance')?.addEventListener('click',()=>openDialog('profile'));host('retake-guidance')?.addEventListener('click',()=>openDialog('placement-intro'))}
function renderAll(){renderPlan();renderSettings()}
window.KOINE_GUIDANCE_UI={render:renderAll,open:openDialog};renderAll();const s=engine.snapshot();if(s.onboarding.status!=='complete')setTimeout(()=>openDialog(s.onboarding.status==='placement'?'placement':'welcome'),0);
})();
