(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.KoinePronunciation=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const STORAGE_KEY='koine-path-pronunciation-v1',SCHEMA=1,MARKS=/[\u0300-\u036f]/u,ACCENTS=new Set(['\u0301','\u0300','\u0342']),ROUGH='\u0314';
const MAPS={
'koine-reconstructed':{αι:'ɛ',ει:'i',οι:'y',ου:'u',αυ:'av',ευ:'ev',ηυ:'ev',γγ:'ŋg',γκ:'ŋg',γξ:'ŋks',γχ:'ŋx',α:'a',β:'v',γ:'ɣ',δ:'ð',ε:'ɛ',ζ:'z',η:'e',θ:'θ',ι:'i',κ:'k',λ:'l',μ:'m',ν:'n',ξ:'ks',ο:'o',π:'p',ρ:'r',σ:'s',τ:'t',υ:'y',φ:'f',χ:'x',ψ:'ps',ω:'o'},
'erasmian':{αι:'ai',ει:'ei',οι:'oi',ου:'u',αυ:'au',ευ:'eu',ηυ:'eu',γγ:'ŋg',γκ:'ŋk',α:'a',β:'b',γ:'g',δ:'d',ε:'e',ζ:'z',η:'eː',θ:'θ',ι:'i',κ:'k',λ:'l',μ:'m',ν:'n',ξ:'ks',ο:'o',π:'p',ρ:'r',σ:'s',τ:'t',υ:'y',φ:'f',χ:'x',ψ:'ps',ω:'oː'},
'modern':{αι:'e',ει:'i',οι:'i',ου:'u',υι:'i',αυ:'av',ευ:'ev',ηυ:'iv',γγ:'ŋg',γκ:'g',μπ:'b',ντ:'d',τσ:'ts',τζ:'dz',α:'a',β:'v',γ:'ɣ',δ:'ð',ε:'e',ζ:'z',η:'i',θ:'θ',ι:'i',κ:'k',λ:'l',μ:'m',ν:'n',ξ:'ks',ο:'o',π:'p',ρ:'r',σ:'s',τ:'t',υ:'i',φ:'f',χ:'x',ψ:'ps',ω:'o'}
};
const clone=v=>JSON.parse(JSON.stringify(v)),safe=s=>{try{return JSON.parse(s)}catch{return null}},iso=d=>new Date(d).toISOString();
class MemoryStorage{constructor(seed={}){this.m=new Map(Object.entries(seed))}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.m.set(k,String(v))}}
function letters(word){const n=String(word||'').normalize('NFD').toLowerCase(),out=[];for(const ch of n){if(MARKS.test(ch)){if(out.length){if(ACCENTS.has(ch))out.at(-1).accent=true;if(ch===ROUGH)out.at(-1).rough=true}continue}if(/[α-ωϲς]/u.test(ch))out.push({ch:ch==='ς'||ch==='ϲ'?'σ':ch,accent:false,rough:false})}return out}
function transcribeWord(word,profile='koine-reconstructed'){const chars=letters(word),map=MAPS[profile]||MAPS['koine-reconstructed'];if(!chars.length)return'';let out='',i=0;if(profile!=='modern'&&chars[0]?.rough)out+='h';while(i<chars.length){const two=(chars[i]?.ch||'')+(chars[i+1]?.ch||''),use=map[two]?2:1,key=use===2?two:chars[i].ch,accent=chars[i].accent||(use===2&&chars[i+1]?.accent);if(accent)out+='ˈ';out+=map[key]||key;i+=use}return out}
function transcribe(text,profile='koine-reconstructed'){return String(text||'').split(/(\s+)/).map(x=>/^\s+$/u.test(x)?x:transcribeWord(x,profile)).join('').trim()}
function initial(now,profile){return{schemaVersion:SCHEMA,settings:{profile,rate:.9,showCue:true},drills:{attempts:0,correct:0,byProfile:{}},listening:{plays:0,words:0},recordings:{sessions:0},history:[],createdAt:iso(now),updatedAt:iso(now)}}
class PronunciationEngine{
 constructor({data,storage=null,clock=()=>new Date()}={}){if(!data?.profiles)throw new Error('PronunciationEngine requires profile data');this.data=data;this.storage=storage||((typeof localStorage!=='undefined')?localStorage:new MemoryStorage());this.clock=clock;const saved=safe(this.storage.getItem(STORAGE_KEY));this.state={...initial(clock(),data.defaultProfile),...(saved||{})};this.state.settings={...initial(clock(),data.defaultProfile).settings,...(this.state.settings||{})};if(!data.profiles[this.state.settings.profile])this.state.settings.profile=data.defaultProfile;this.persist()}
 persist(){this.state.updatedAt=iso(this.clock());this.storage.setItem(STORAGE_KEY,JSON.stringify(this.state))}snapshot(){return clone(this.state)}profile(){return this.data.profiles[this.state.settings.profile]}setProfile(id){if(!this.data.profiles[id])throw new Error('Unknown pronunciation profile');this.state.settings.profile=id;this.persist();return this.profile()}setRate(v){this.state.settings.rate=Math.max(.55,Math.min(1.35,Number(v)||.9));this.persist();return this.state.settings.rate}cue(text,profile=this.state.settings.profile){return transcribe(text,profile)}
 answerDrill(id,index){const d=this.data.drills.find(x=>x.id===id);if(!d)throw new Error('Unknown pronunciation drill');const ok=Number(index)===d.answer;this.state.drills.attempts++;if(ok)this.state.drills.correct++;const p=this.state.drills.byProfile[d.profile]||{attempts:0,correct:0};p.attempts++;if(ok)p.correct++;this.state.drills.byProfile[d.profile]=p;this.state.history.unshift({type:'drill',id,profile:d.profile,correct:ok,at:iso(this.clock())});this.state.history=this.state.history.slice(0,120);this.persist();return ok}
 notePlay(words=1){this.state.listening.plays++;this.state.listening.words+=Number(words)||0;this.persist()}noteRecording(){this.state.recordings.sessions++;this.persist()}stats(){return{profile:this.state.settings.profile,drillAttempts:this.state.drills.attempts,drillAccuracy:this.state.drills.attempts?Math.round(this.state.drills.correct/this.state.drills.attempts*100):null,plays:this.state.listening.plays,recordings:this.state.recordings.sessions}}
 availableModernVoice(){if(typeof speechSynthesis==='undefined')return null;const voices=speechSynthesis.getVoices();return voices.find(v=>/^el(-|_)?/i.test(v.lang))||null}
 canSpeak(){return this.state.settings.profile==='modern'&&!!this.availableModernVoice()}
 speak(text,{onWord=null,onEnd=null}={}){if(this.state.settings.profile!=='modern')return{ok:false,reason:'Historical profiles require a verified recording pack; Modern Greek TTS is not substituted.'};if(typeof speechSynthesis==='undefined'||typeof SpeechSynthesisUtterance==='undefined')return{ok:false,reason:'Speech synthesis unavailable.'};const voice=this.availableModernVoice();if(!voice)return{ok:false,reason:'No el-GR browser voice is installed.'};speechSynthesis.cancel();const words=String(text||'').trim().split(/\s+/).filter(Boolean);let i=0;const next=()=>{if(i>=words.length){this.notePlay(words.length);onEnd?.();return}onWord?.(i,words[i]);const u=new SpeechSynthesisUtterance(words[i]);u.lang='el-GR';u.voice=voice;u.rate=this.state.settings.rate;u.onend=()=>{i++;next()};u.onerror=()=>{i++;next()};speechSynthesis.speak(u)};next();return{ok:true,voice:voice.name,words:words.length}}
 stop(){if(typeof speechSynthesis!=='undefined')speechSynthesis.cancel()}
}
return{STORAGE_KEY,SCHEMA,MAPS,MemoryStorage,letters,transcribeWord,transcribe,PronunciationEngine};
});