(()=>{
'use strict';
const api=window.KoinePublication,lib=window.KOINE_SOURCE_LIBRARY,syn=window.KOINE_RESEARCH_SYNTHESIS;if(!api||!lib||!syn)return;
const engine=new api.PublicationEngine();window.KOINE_PUBLICATION=engine;
if(typeof titles!=='undefined')titles.publication=['Publication','Format citations, bibliography templates, notes, and publication exports.'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav=document.querySelector('.nav'),anchor=nav?.querySelector('[data-view="synthesis"]')||nav?.querySelector('[data-view="sources"]');if(nav&&!nav.querySelector('[data-view="publication"]')){const b=document.createElement('button');b.dataset.view='publication';b.textContent='Publication';anchor?.after(b);b.addEventListener('click',()=>openView('publication'))}
const main=document.querySelector('.content'),tutor=document.querySelector('#tutor'),section=document.createElement('section');section.id='publication';section.className='view';main?.insertBefore(section,tutor||null);
function dossier(){return syn.getDossier?.()||null}function resolveResearch(id){return lib.sourceForResearchEntry?.(id)||null}
function sourceIds(d){return api.sourceIdsForDossier(d,resolveResearch)}function sources(d){return sourceIds(d).map(id=>lib.getSource(id))}
function download(text,name,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0)}
function fileStem(d){return String(d?.title||'exegetical-dossier').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'exegetical-dossier'}
function optionRows(values,current,label){return values.map(v=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(label(v))}</option>`).join('')}
function render(){const d=dossier(),p=engine.getProfile();section.innerHTML=`<div class="eyebrow">Publication studio · V1.11</div><h1>Format the dossier without rewriting the evidence.</h1><p class="lede">Citation styles, note placement, bibliography templates, and publication profiles consume V1.10 sources and V1.9 dossier links. Formatting never changes the source library, citation graph, or canonical mastery.</p>${d?renderWorkspace(d,p):renderEmpty()}`;if(d)bind(d,p)}
function renderEmpty(){return`<div class="panel publication-empty"><h2>No active dossier</h2><p>Open or create a V1.9 dossier first. Publication formatting is derived from an existing dossier rather than creating a parallel research document.</p><button class="btn primary" id="publication-open-synthesis">Open Synthesis</button></div>`}
function profileOptions(id){return engine.listProfiles().map(p=>`<option value="${esc(p.id)}" ${p.id===id?'selected':''}>${esc(p.name)}</option>`).join('')}
function renderWorkspace(d,p){const ids=sourceIds(d),srcs=sources(d),occ=api.citationOccurrences(d,resolveResearch);return`<div class="publication-summary"><div><span>Linked sources</span><strong>${ids.length}</strong></div><div><span>Citation occurrences</span><strong>${occ.length}</strong></div><div><span>Placement</span><strong>${esc(p.placement)}</strong></div><div><span>Style</span><strong>${esc(api.style(p.styleId).name)}</strong></div></div><div class="publication-layout"><article><div class="panel" id="publication-profile">${renderProfile(p,d)}</div><div class="panel" id="publication-preview">${renderPreview(d,p,srcs)}</div></article><aside><div class="panel" id="publication-sources">${renderSources(srcs,p)}</div><div class="panel" id="publication-export">${renderExport(d,p)}</div></aside></div>`}
function renderProfile(p,d){return`<div class="section-head"><div><h2>Publication profile</h2><p>Reusable formatting preferences only. Style names below are Koinē house templates, not external style certifications.</p></div></div><div class="publication-profile-row"><label>Profile<select id="pub-profile-select">${profileOptions(p.id)}</select></label><button class="btn" id="pub-new-profile">Duplicate profile</button><button class="btn text" id="pub-delete-profile" ${engine.listProfiles().length<=1?'disabled':''}>Delete</button></div><div class="publication-grid"><label>Profile name<input id="pub-name" value="${esc(p.name)}"></label><label>Citation style<select id="pub-style">${optionRows(api.STYLE_IDS,p.styleId,x=>api.style(x).name)}</select></label><label>Citation placement<select id="pub-placement">${optionRows(api.PLACEMENTS,p.placement,x=>x[0].toUpperCase()+x.slice(1))}</select></label><label>Bibliography template<select id="pub-bib-template">${optionRows(api.BIB_TEMPLATES,p.bibliographyTemplate,x=>x==='standard'?'Standard alphabetical':x==='keyed'?'Citation-key bibliography':'Annotated bibliography')}</select></label><label>Bibliography heading<input id="pub-bib-heading" value="${esc(p.bibliographyHeading)}"></label><label>Notes heading<input id="pub-notes-heading" value="${esc(p.notesHeading)}"></label><label>Document title<input id="pub-doc-title" value="${esc(p.document.title||d.title)}"></label><label>Subtitle<input id="pub-doc-subtitle" value="${esc(p.document.subtitle)}"></label><label>Author<input id="pub-doc-author" value="${esc(p.document.author)}"></label><label>Date<input id="pub-doc-date" value="${esc(p.document.date)}"></label></div><div class="publication-checks"><label><input type="checkbox" id="pub-title-page" ${p.includeTitlePage?'checked':''}> Title metadata</label><label><input type="checkbox" id="pub-bibliography" ${p.includeBibliography?'checked':''}> Bibliography</label><label><input type="checkbox" id="pub-evidence" ${p.includeEvidenceAppendix?'checked':''}> Evidence appendix</label><label><input type="checkbox" id="pub-readings" ${p.includeAlternativeReadings?'checked':''}> Alternative readings</label><label><input type="checkbox" id="pub-theological" ${p.includeTheologicalSynthesis?'checked':''}> Theological synthesis</label><label><input type="checkbox" id="pub-limitations" ${p.includeLimitations?'checked':''}> Limitations</label><label><input type="checkbox" id="pub-keys" ${p.includeCitationKeys?'checked':''}> Citation keys</label><label><input type="checkbox" id="pub-source-notes" ${p.includeSourceNotes?'checked':''}> Source notes in annotated bibliography</label></div><div class="publication-actions"><button class="btn primary" id="pub-save-profile">Save profile</button><span class="publication-status" id="pub-profile-status" role="status" aria-live="polite"></span></div><p class="synthesis-boundary">${esc(api.style(p.styleId).certification)}</p>`}
function renderPreview(d,p,srcs){let text='';try{text=engine.exportPublication({dossier:d,sources:srcs,resolveSource:resolveResearch,profile:p,format:'markdown'})}catch(e){text=e.message}return`<div class="section-head"><div><h2>Publication preview</h2><p>Markdown preview of the active dossier with the saved profile.</p></div></div><pre class="publication-preview-text">${esc(text.slice(0,18000))}</pre>`}
function renderSources(srcs,p){return`<div class="section-head"><div><h2>Bibliography sources</h2><p>Only structured V1.10 sources actually linked through V1.8 evidence are eligible.</p></div></div><ol class="publication-source-list">${srcs.map(s=>`<li><strong>@${esc(s.citationKey)}</strong><span>${esc(api.bibliographyEntry(s,p.styleId))}</span></li>`).join('')||'<li>No structured sources linked to this dossier.</li>'}</ol>`}
function renderExport(d,p){return`<h2>Publication export</h2><p>Exports are generated locally from the current dossier and structured source metadata.</p><div class="publication-export-actions"><button class="btn primary" data-pub-export="markdown">Markdown</button><button class="btn" data-pub-export="html">Standalone HTML</button><button class="btn" data-pub-export="text">Plain text</button></div><p class="publication-status" id="pub-export-status" role="status" aria-live="polite"></p><p class="synthesis-boundary">Export does not certify scholarly correctness, style-guide compliance, peer review, or publication acceptance.</p>`}
function readPatch(){return{name:section.querySelector('#pub-name').value,styleId:section.querySelector('#pub-style').value,placement:section.querySelector('#pub-placement').value,bibliographyTemplate:section.querySelector('#pub-bib-template').value,bibliographyHeading:section.querySelector('#pub-bib-heading').value,notesHeading:section.querySelector('#pub-notes-heading').value,includeTitlePage:section.querySelector('#pub-title-page').checked,includeBibliography:section.querySelector('#pub-bibliography').checked,includeEvidenceAppendix:section.querySelector('#pub-evidence').checked,includeAlternativeReadings:section.querySelector('#pub-readings').checked,includeTheologicalSynthesis:section.querySelector('#pub-theological').checked,includeLimitations:section.querySelector('#pub-limitations').checked,includeCitationKeys:section.querySelector('#pub-keys').checked,includeSourceNotes:section.querySelector('#pub-source-notes').checked,document:{title:section.querySelector('#pub-doc-title').value,subtitle:section.querySelector('#pub-doc-subtitle').value,author:section.querySelector('#pub-doc-author').value,date:section.querySelector('#pub-doc-date').value}}}
function bind(d,p){section.querySelector('#pub-profile-select').onchange=e=>{engine.setActive(e.target.value);render()};section.querySelector('#pub-new-profile').onclick=()=>{engine.createProfile({...p,name:`${p.name} copy`,id:undefined});render()};section.querySelector('#pub-delete-profile').onclick=()=>{try{engine.deleteProfile(p.id);render()}catch(e){section.querySelector('#pub-profile-status').textContent=e.message}};section.querySelector('#pub-save-profile').onclick=()=>{try{engine.updateProfile(p.id,readPatch());section.querySelector('#pub-profile-status').textContent='Publication profile saved.';render()}catch(e){section.querySelector('#pub-profile-status').textContent=e.message}};section.querySelectorAll('[data-pub-export]').forEach(b=>b.onclick=()=>{const format=b.dataset.pubExport,srcs=sources(d);try{const text=engine.exportPublication({dossier:d,sources:srcs,resolveSource:resolveResearch,profile:engine.getProfile(),format}),stem=fileStem(d);if(format==='html')download(text,`${stem}.html`,'text/html;charset=utf-8');else if(format==='text')download(text,`${stem}.txt`,'text/plain;charset=utf-8');else download(text,`${stem}.md`,'text/markdown;charset=utf-8');section.querySelector('#pub-export-status').textContent=`${format==='markdown'?'Markdown':format==='html'?'HTML':'Plain-text'} export generated.`}catch(e){section.querySelector('#pub-export-status').textContent=e.message}})}
window.KOINE_PUBLICATION_UI={render,open:()=>{window.KOINE_APP_OPEN_VIEW?.('publication');render()}};render();
})();