(()=>{
'use strict';
const api=window.KoineOffline;if(!api)return;const engine=new api.OfflineEngine();window.KOINE_OFFLINE_ENGINE=engine;
let installPrompt=null,registration=null,updateReady=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]));
function ensureUi(){
  if(typeof titles!=='undefined')titles.offline=['Offline','Install Koinē Path and choose exactly which Greek data stays on this device.'];
  const nav=document.querySelector('.nav');if(nav&&!nav.querySelector('[data-view="offline"]')){const b=document.createElement('button');b.dataset.view='offline';b.textContent='Offline';const audio=nav.querySelector('[data-view="audio"]');(audio||nav.lastElementChild)?.after(b);b.addEventListener('click',()=>openView('offline'));}
  const main=document.querySelector('.content');if(main&&!document.querySelector('#offline')){const s=document.createElement('section');s.id='offline';s.className='view';main.appendChild(s);}
  const top=document.querySelector('.top');if(top&&!document.querySelector('#pwa-connection')){const span=document.createElement('span');span.id='pwa-connection';span.className='pwa-connection';top.appendChild(span);}
}
function connectionText(){return navigator.onLine?'Online':'Offline'}
function renderConnection(){const el=document.querySelector('#pwa-connection');if(el){el.textContent=connectionText();el.dataset.online=String(navigator.onLine)}}
function notifyUpdate(){updateReady=true;let b=document.querySelector('#pwa-update-banner');if(!b){b=document.createElement('div');b.id='pwa-update-banner';b.className='pwa-update-banner';document.body.appendChild(b)}b.innerHTML='<span>A new Koinē Path version is ready.</span><button class="btn primary" id="pwa-apply-update">Update now</button>';b.querySelector('#pwa-apply-update').onclick=()=>{registration?.waiting?.postMessage({type:'SKIP_WAITING'})};}
async function registerServiceWorker(){if(!('serviceWorker'in navigator))return;try{registration=await navigator.serviceWorker.register('./sw.js',{scope:'./'});if(registration.waiting)notifyUpdate();registration.addEventListener('updatefound',()=>{const w=registration.installing;if(!w)return;w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)notifyUpdate()})});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload());}catch(err){console.warn('PWA registration failed',err)}}
function progress(host,label){return ({done,total})=>{if(host)host.textContent=`${label}: ${done}/${total}`}}
async function perform(action,label){const note=document.querySelector('#offline-note');if(note)note.textContent=`${label}…`;try{await action(progress(note,label));if(note)note.textContent=`${label} complete.`;await render()}catch(err){if(note)note.textContent=err.message||String(err)}}
async function render(){ensureUi();renderConnection();const host=document.querySelector('#offline');if(!host)return;let manifest=null,status=null,estimate=null,persistent=null;try{manifest=await engine.loadManifest(true);status=await engine.status();estimate=await engine.estimate();persistent=await engine.persistent()}catch(err){host.innerHTML=`<div class="eyebrow">PWA & offline · BG13</div><h1>Offline manager unavailable.</h1><p class="lede">${esc(err.message)}</p><p>The app shell may still work offline if it was previously installed. Corpus management requires the generated corpus manifest.</p>`;return}
  const installed=window.matchMedia?.('(display-mode: standalone)').matches||navigator.standalone===true;
  const swState=registration?'Registered':(('serviceWorker'in navigator)?'Initializing':'Unsupported');
  const storage=estimate?`${estimate.usageText} of ${estimate.quotaText}${estimate.percent!=null?` · ${estimate.percent}%`:''}`:'Storage estimate unavailable';
  host.innerHTML=`<div class="eyebrow">PWA & offline · BG13</div><div class="offline-title"><div><h1>Install the app. Download only what you need.</h1><p class="lede">The application shell works offline after installation/first successful cache. Greek corpus downloads are explicit and revision-aware; the full NT is never required for first launch.</p></div><span class="offline-state" data-online="${navigator.onLine}">${connectionText()}</span></div>
  <div class="offline-grid"><section class="panel"><div class="section-head"><div><h2>Application</h2><p>Versioned shell cache · GitHub Pages-safe scope.</p></div></div><div class="offline-kv"><span>Install state</span><strong>${installed?'Installed / standalone':'Browser tab'}</strong><span>Service worker</span><strong>${swState}</strong><span>Update</span><strong>${updateReady?'Ready to apply':'Current'}</strong></div><div class="offline-actions"><button class="btn primary" id="pwa-install" ${installPrompt&&!installed?'':'disabled'}>Install Koinē Path</button><button class="btn" id="pwa-check-update">Check for update</button></div><small>Install availability is controlled by the browser. HTTPS is required outside localhost.</small></section>
  <section class="panel"><div class="section-head"><div><h2>Storage</h2><p>Browser-reported values are estimates.</p></div></div><div class="offline-kv"><span>Origin storage</span><strong>${esc(storage)}</strong><span>Persistence</span><strong>${persistent===true?'Granted':persistent===false?'Best effort':'Unknown'}</strong><span>Corpus revision</span><strong class="mono">${esc(status.revision.slice(0,12))}</strong><span>Stale corpus caches</span><strong>${status.staleCaches.length}</strong></div><div class="offline-actions"><button class="btn" id="pwa-persist" ${persistent?'disabled':''}>Request persistent storage</button><button class="btn" id="pwa-clear-stale" ${status.staleCaches.length?'':'disabled'}>Remove old corpus versions</button></div></section></div>
  <div class="panel"><div class="section-head"><div><h2>Offline packs</h2><p>Core manifest + lemma frequency are included with every book/program pack. The full-NT pack additionally stores the exact-corpus lexical index.</p></div><span>${status.downloadedBooks}/${status.totalBooks} books stored</span></div><div class="offline-pack-grid"><button class="offline-pack" data-pack="1john"><strong>1 John</strong><span>Unit 45 fluency program</span></button><button class="offline-pack" data-pack="mark"><strong>Mark</strong><span>Unit 46 narrative program</span></button><button class="offline-pack" data-pack="phil"><strong>Philippians</strong><span>Unit 47 epistolary program</span></button><button class="offline-pack" data-pack="fluency"><strong>All fluency books</strong><span>1 John + Mark + Philippians</span></button><button class="offline-pack" id="offline-lexical"><strong>Lexical index</strong><span>5,461 exact-corpus lemma profiles</span></button><button class="offline-pack strong" id="offline-full"><strong>Entire Greek NT</strong><span>27 books + frequency + lexical index</span></button></div><p id="offline-note" class="offline-note"></p></div>
  <div class="panel"><div class="section-head"><div><h2>Books</h2><p>Download or remove individual BG6 book chunks.</p></div><button class="btn" id="offline-clear-current">Remove current corpus downloads</button></div><div class="offline-books">${manifest.books.map(b=>`<div class="offline-book"><div><strong>${esc(b.name)}</strong><small>${b.chapters} ch · ${b.tokens.toLocaleString()} tokens</small></div><span class="offline-badge" data-stored="${status.books[b.id]}">${status.books[b.id]?'Stored':'Online only'}</span><button class="btn" data-book="${b.id}" data-action="${status.books[b.id]?'remove':'download'}">${status.books[b.id]?'Remove':'Download'}</button></div>`).join('')}</div></div>
  <div class="panel offline-boundary"><strong>Learner-state boundary</strong><p>Removing offline caches never deletes localStorage learner state: mastery, SRS cards, reader history, bookmarks, fluency history, exegesis notebooks, pronunciation settings, and other personal progress remain intact.</p></div>`;
  host.querySelector('#pwa-install').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();await installPrompt.userChoice.catch(()=>null);installPrompt=null;render()};
  host.querySelector('#pwa-check-update').onclick=()=>registration?.update();host.querySelector('#pwa-persist').onclick=async()=>{await engine.requestPersistence();render()};host.querySelector('#pwa-clear-stale').onclick=async()=>{await engine.clearStale();render()};
  host.querySelectorAll('[data-pack]').forEach(b=>b.onclick=()=>perform(cb=>engine.downloadPack(b.dataset.pack,{onProgress:cb}),`Downloading ${b.querySelector('strong').textContent}`));
  host.querySelector('#offline-lexical').onclick=()=>perform(cb=>engine.downloadLexical({onProgress:cb}),'Downloading lexical index');host.querySelector('#offline-full').onclick=()=>perform(cb=>engine.downloadFull({onProgress:cb}),'Downloading complete Greek NT');
  host.querySelector('#offline-clear-current').onclick=async()=>{await engine.clearCurrent();render()};host.querySelectorAll('[data-book]').forEach(b=>b.onclick=async()=>{if(b.dataset.action==='remove'){await engine.removeBook(b.dataset.book);render()}else perform(cb=>engine.downloadBook(b.dataset.book,{onProgress:cb}),`Downloading ${b.dataset.book}`)});
}
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;if(document.querySelector('#offline')?.classList.contains('active'))render()});window.addEventListener('appinstalled',()=>{installPrompt=null;render()});window.addEventListener('online',()=>{renderConnection();if(document.querySelector('#offline')?.classList.contains('active'))render()});window.addEventListener('offline',()=>{renderConnection();if(document.querySelector('#offline')?.classList.contains('active'))render()});
document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.view==='offline')setTimeout(render,0)}));
ensureUi();registerServiceWorker();renderConnection();const requested=new URLSearchParams(location.search).get('view');if(requested&&document.querySelector(`#${CSS.escape(requested)}`))setTimeout(()=>openView(requested),0);window.renderOfflineManager=render;
})();
