(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.KoineReadingFluency=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const STORAGE_KEY='koine-path-reading-fluency-v1',SCHEMA=1,MAX_HISTORY=200;
const clone=v=>JSON.parse(JSON.stringify(v));const safe=s=>{try{return JSON.parse(s)}catch{return null}};const iso=d=>new Date(d).toISOString();const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n));
class MemoryStorage{constructor(seed={}){this.m=new Map(Object.entries(seed))}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.m.set(k,String(v))}}
function initial(now){return{schemaVersion:SCHEMA,settings:{program:'1john',mode:'guided'},active:null,history:[],createdAt:iso(now),updatedAt:iso(now)}}
function countClauses(tokens){return Math.max(1,tokens.filter(t=>/[.;·;?]/u.test(String(t.text||''))).length)}
function durationMinutes(start,end){return Math.max(1/60,(new Date(end)-new Date(start))/60000)}
function metrics(pass,tokenCount,clauses){if(!pass?.startedAt||!pass?.endedAt)return null;const mins=durationMinutes(pass.startedAt,pass.endedAt),wpm=tokenCount/mins,cpm=clauses/mins;return{minutes:Math.round(mins*100)/100,wpm:Math.round(wpm),clausesPerMinute:Math.round(cpm*10)/10,unknownRate:Math.round((pass.unknown||0)/Math.max(1,tokenCount)*1000)/10,assistanceRate:Math.round((pass.assistance||0)/Math.max(1,tokenCount)*1000)/10,interruptions:pass.interruptions||0}}
function readiness(history){const done=history.filter(x=>x.status==='complete').slice(0,8);if(done.length<5)return{ready:false,reason:`${done.length}/5 completed fluency sessions`,sessions:done.length};const recent=done.slice(0,5),avg=k=>recent.reduce((s,x)=>s+Number(x.summary?.[k]||0),0)/recent.length,comprehension=avg('comprehension'),unknown=avg('unknownRate'),assist=avg('assistanceRate'),long=recent.filter(x=>(x.tokenCount||0)>=100).length;const ready=comprehension>=80&&unknown<=12&&assist<=8&&long>=3;return{ready,reason:ready?'R4 practicum criteria met':'Need ≥80% comprehension, ≤12% unknown rate, ≤8% analysis assistance, and 3/5 passages ≥100 tokens',sessions:recent.length,comprehension:Math.round(comprehension),unknownRate:Math.round(unknown*10)/10,assistanceRate:Math.round(assist*10)/10,longPassages:long}}
class FluencyEngine{
 constructor({programs,learningEngine=null,vocabularyEngine=null,storage=null,clock=()=>new Date(),fetchFn=null,basePath='generated/corpus/books',unitForToken=null}={}){if(!programs?.passages)throw new Error('FluencyEngine requires reviewed fluency programs.');this.data=programs;this.learning=learningEngine;this.vocab=vocabularyEngine;this.storage=storage||((typeof localStorage!=='undefined')?localStorage:new MemoryStorage());this.clock=clock;this.fetchFn=fetchFn||((typeof fetch!=='undefined')?fetch.bind(globalThis):null);this.basePath=basePath;this.unitForToken=unitForToken||(()=>50);this.cache=new Map();this.state={...initial(clock()),...(safe(this.storage.getItem(STORAGE_KEY))||{})};this.state.settings={...initial(clock()).settings,...(this.state.settings||{})};this.persist()}
 persist(){this.state.updatedAt=iso(this.clock());this.storage.setItem(STORAGE_KEY,JSON.stringify(this.state))}snapshot(){return clone(this.state)}
 async loadBook(id){if(this.cache.has(id))return this.cache.get(id);if(!this.fetchFn)throw new Error('Corpus fetch unavailable');const r=await this.fetchFn(`${this.basePath}/${encodeURIComponent(id)}.json`,{cache:'force-cache'});if(!r.ok)throw new Error(`${id}: HTTP ${r.status}`);const b=await r.json();this.cache.set(id,b);return b}
 passageDef(id){return this.data.passages.find(p=>p.id===id)||null}
 async materialize(def){def=typeof def==='string'?this.passageDef(def):def;if(!def)throw new Error('Unknown fluency passage');const b=await this.loadBook(def.ref.book),chapter=b.chapters?.[String(def.ref.chapter)];if(!chapter)throw new Error(`Missing chapter ${def.ref.book}.${def.ref.chapter}`);const verses=[];for(let v=def.ref.startVerse;v<=def.ref.endVerse;v++)if(chapter[String(v)])verses.push({verse:v,tokens:chapter[String(v)]});const tokens=verses.flatMap(x=>x.tokens);if(!tokens.length)throw new Error(`Empty passage ${def.id}`);return{...clone(def),book:b.book,verses,tokens,text:tokens.map(t=>t.text).join(' '),tokenCount:tokens.length,clauses:countClauses(tokens),reference:`${b.book.name||def.ref.book} ${def.ref.chapter}:${def.ref.startVerse}${def.ref.endVerse!==def.ref.startVerse?`–${def.ref.endVerse}`:''}`}}
 knownLemma(lemma){const cards=Object.values(this.vocab?.state?.cards||{}).filter(c=>c.type==='lemma-recognition'&&c.lemma===lemma&&!c.suspended);return cards.some(c=>c.reps>=2&&c.lastRating!=='again'&&!c.leech)}
 suitability(material){const tokens=material.tokens,known=tokens.filter(t=>this.knownLemma(t.lemma)).length,vocabCoverage=Math.round(known/Math.max(1,tokens.length)*100);let accessible=0;for(const t of tokens){const id=this.unitForToken(t),u=this.learning?.getUnit?.(id);if(!u||u.accessible)accessible++}const grammarCoverage=Math.round(accessible/Math.max(1,tokens.length)*100);return{vocabCoverage,grammarCoverage,score:Math.round((vocabCoverage*.55+grammarCoverage*.45))}}
 candidates(program=this.state.settings.program){const completed=new Set(this.state.history.filter(x=>x.status==='complete').map(x=>x.passageId));return this.data.passages.filter(p=>program==='all'||p.program===program).map(p=>({...clone(p),seen:completed.has(p.id)}))}
 async recommend(program=this.state.settings.program){const candidates=this.candidates(program),mats=[];for(const p of candidates){try{const m=await this.materialize(p),s=this.suitability(m);mats.push({...m,suitability:s})}catch{}}if(!mats.length)return null;mats.sort((a,b)=>Number(a.seen)-Number(b.seen)||Math.abs(88-b.suitability.score)-Math.abs(88-a.suitability.score)||a.tokenCount-b.tokenCount);return mats[0]}
 setProgram(id){if(id!=='all'&&!this.data.programs[id])throw new Error('Unknown fluency program');this.state.settings.program=id;this.persist()}
 start(material,{mode='guided',cold=false}={}){if(this.state.active)throw new Error('A fluency session is already active.');const now=iso(this.clock());this.state.active={id:`fluency.${Date.now()}`,passageId:material.id||`custom.${material.ref.book}.${material.ref.chapter}.${material.ref.startVerse}.${material.ref.endVerse}`,unitId:material.unitId||50,reference:material.reference,program:material.program||'independent',mode,cold:!!cold,status:'first-pass',tokenCount:material.tokenCount,clauses:material.clauses,startedAt:now,firstPass:{startedAt:now,endedAt:null,unknown:0,assistance:0,interruptions:0},checkpoint:{answered:false,correct:null},analysis:null,reread:null,completedAt:null};this.persist();return clone(this.state.active)}
 markUnknown(){const s=this.state.active;if(!s||s.status!=='first-pass')return false;s.firstPass.unknown++;s.firstPass.interruptions++;this.persist();return true}
 finishFirstPass(){const s=this.state.active;if(!s||s.status!=='first-pass')throw new Error('First pass is not active');s.firstPass.endedAt=iso(this.clock());s.status='checkpoint';this.persist();return metrics(s.firstPass,s.tokenCount,s.clauses)}
 answerCheckpoint(correct){const s=this.state.active;if(!s||s.status!=='checkpoint')throw new Error('Checkpoint is not active');s.checkpoint={answered:true,correct:!!correct,at:iso(this.clock())};if(this.learning){const u=this.learning.getUnit(s.unitId);if(u?.accessible&&correct)this.learning.recordEvidence({unitId:s.unitId,dimension:'reading',correct:true,hintLevel:'none',itemId:s.passageId,source:'fluency-comprehension',confidence:.72});else this.learning.recordExposure({unitId:s.unitId,itemId:s.passageId,source:'fluency-comprehension'})}s.status='analysis';s.analysis={startedAt:iso(this.clock()),endedAt:null,unknown:0,assistance:0,interruptions:0};this.persist();return clone(s.checkpoint)}
 assist(){const s=this.state.active;if(!s||s.status!=='analysis')return false;s.analysis.assistance++;s.analysis.interruptions++;this.persist();return true}
 markAnalysisUnknown(){const s=this.state.active;if(!s||s.status!=='analysis')return false;s.analysis.unknown++;s.analysis.interruptions++;this.persist();return true}
 finishAnalysis(){const s=this.state.active;if(!s||s.status!=='analysis')throw new Error('Analysis pass is not active');s.analysis.endedAt=iso(this.clock());s.status='reread';s.reread={startedAt:iso(this.clock()),endedAt:null,unknown:0,assistance:0,interruptions:0};this.persist();return metrics(s.analysis,s.tokenCount,s.clauses)}
 finishReread(){const s=this.state.active;if(!s||s.status!=='reread')throw new Error('Reread is not active');s.reread.endedAt=iso(this.clock());s.status='complete';s.completedAt=iso(this.clock());const first=metrics(s.firstPass,s.tokenCount,s.clauses),analysis=metrics(s.analysis,s.tokenCount,s.clauses),reread=metrics(s.reread,s.tokenCount,s.clauses),gain=first?.wpm?Math.round((reread.wpm-first.wpm)/first.wpm*100):0;s.summary={firstWpm:first?.wpm||0,rereadWpm:reread?.wpm||0,rereadGain:gain,unknownRate:first?.unknownRate||0,assistanceRate:analysis?.assistanceRate||0,comprehension:s.checkpoint.correct?100:0,firstPass:first,analysis,reread};const done=clone(s);this.state.history.unshift(done);this.state.history=this.state.history.slice(0,MAX_HISTORY);this.state.active=null;this.persist();return done}
 cancel(){this.state.active=null;this.persist()}
 stats(){const done=this.state.history.filter(x=>x.status==='complete'),avg=k=>done.length?done.reduce((s,x)=>s+Number(x.summary?.[k]||0),0)/done.length:0,days=new Set(done.map(x=>String(x.completedAt||'').slice(0,10)).filter(Boolean));return{sessions:done.length,passages:new Set(done.map(x=>x.passageId)).size,readingDays:days.size,avgFirstWpm:Math.round(avg('firstWpm')),avgComprehension:Math.round(avg('comprehension')),avgUnknownRate:Math.round(avg('unknownRate')*10)/10,avgAssistanceRate:Math.round(avg('assistanceRate')*10)/10,readiness:readiness(done)}}
 history(){return clone(this.state.history)}
}
return{STORAGE_KEY,SCHEMA,MemoryStorage,countClauses,metrics,readiness,FluencyEngine};
});