(function(){
'use strict';
const sessions=window.KOINE_SESSION_ENGINE,guidance=window.KOINE_GUIDANCE_ENGINE;if(!sessions||!guidance)return;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const viewLabel=v=>({today:'Today',learn:'Learn',drill:'Morphology',read:'Read',tutor:'Tutor',review:'Review',progress:'Progress'}[v]||v);
const engagedLabel=s=>Number(s||0)<60?'<1 min':`${Math.round(Number(s)/60)} min`;
const displayTask=t=>window.KOINE_READING_GOALS_UI?.sessionTask?.(t)||t;
function goTask(task){sessions.setContextView(task.view);if(task.view==='read'&&window.KOINE_READING_GOALS_UI?.currentTask?.()){window.KOINE_READING_GOALS_UI.openNext();return}window.KOINE_APP_OPEN_VIEW?.(task.view);if(task.view==='learn'&&task.unitId)window.KOINE_COURSE_UI?.openUnit?.(task.unitId)}
function renderToday(){
  const host=$('daily-session');if(!host)return;const active=sessions.getActiveSession(),plan=guidance.getGuidedPlan(),guided=$('guided-plan');if(guided)guided.hidden=!!active;
  if(!active){
    if(plan.status!=='ready')host.innerHTML=`<div class="daily-session panel session-empty"><div class="eyebrow">Daily session</div><h2>Set up your study path first.</h2><p>Daily sessions use your goal, workload, placement routing, and the canonical learning-engine recommendation.</p><button class="btn primary" id="session-setup">Set up study path</button></div>`;
    else host.innerHTML=`<div class="daily-session panel session-empty"><div class="session-head"><div><div class="eyebrow">Daily session · V1.4</div><h2>${esc(plan.minutes)}-minute study session</h2><p>${esc(plan.summary)}</p></div><span class="session-status"><i></i>Ready</span></div><div class="session-summary-grid"><div><small>Planned time</small><strong>${plan.minutes} min</strong></div><div><small>Tasks</small><strong>${plan.tasks.length}</strong></div><div><small>Primary focus</small><strong>${esc(viewLabel(plan.tasks[0]?.view||'learn'))}</strong></div><div><small>Mode</small><strong>${plan.mode==='accelerated-validation'?'Validate':'Guided'}</strong></div></div><div class="session-controls"><button class="btn primary" id="session-start">Start session</button></div><p class="session-time-note">Active time is counted only while Koinē Path is open, visible, and the session is not paused.</p></div>`;
    $('session-setup')?.addEventListener('click',()=>window.KOINE_GUIDANCE_UI?.open?.());
    $('session-start')?.addEventListener('click',()=>{sessions.startSession(plan,{goal:plan.goal});sessions.setContextView('today');renderAll()});return;
  }
  const done=active.tasks.filter(t=>t.completedAt).length,status=active.status==='paused'?'Paused':'In progress';
  host.innerHTML=`<div class="daily-session panel"><div class="session-head"><div><div class="eyebrow">Daily session</div><h2>${done===active.tasks.length?'Plan tasks complete':'Continue your session'}</h2><p>${engagedLabel(active.engagedSeconds)} active · ${done}/${active.tasks.length} tasks · ${active.plannedMinutes} min planned</p></div><span class="session-status"><i></i>${status}</span></div><div class="session-task-list">${active.tasks.map(t=>{const d=displayTask(t);return `<div class="session-task"><label class="session-task-main"><input type="checkbox" data-session-check="${esc(t.id)}" ${t.completedAt?'checked':''}><span><strong>${esc(d.title)}</strong><span>${esc(viewLabel(t.view))} · ${t.plannedMinutes} min${d.readingReference?` · ${esc(d.readingReference)} · ${esc(d.readingAssistance)} suggested`:t.unitId?` · Unit ${t.unitId}`:''}</span></span></label><button class="btn" data-session-open="${esc(t.id)}">Open</button></div>`}).join('')}</div><p class="session-complete-note">Checking a task records session workflow only. It does not award mastery, pass a stage, or alter canonical evidence.</p><div class="session-controls"><button class="btn" id="session-pause">${active.status==='paused'?'Resume':'Pause'}</button><button class="btn primary" id="session-finish">Finish session</button></div><p class="session-time-note">Closing or backgrounding the app adds no study time. An unfinished session remains available after reload.</p></div>`;
  host.querySelectorAll('[data-session-check]').forEach(box=>box.addEventListener('change',()=>{sessions.markTaskComplete(box.dataset.sessionCheck,box.checked);renderAll()}));
  host.querySelectorAll('[data-session-open]').forEach(btn=>btn.addEventListener('click',()=>{const t=active.tasks.find(x=>x.id===btn.dataset.sessionOpen);if(t)goTask(t)}));
  $('session-pause')?.addEventListener('click',()=>{active.status==='paused'?sessions.resume():sessions.pause();renderAll()});
  $('session-finish')?.addEventListener('click',()=>{const current=sessions.getActiveSession(),allDone=current.tasks.every(t=>t.completedAt);if(!allDone&&!globalThis.confirm('Finish this session with unfinished tasks? They will remain visible in your session history as incomplete.'))return;sessions.finishSession({reason:allDone?'completed':'manual'});renderAll()});
}
function analyticsCard(label,value,sub,progress=null){return `<div class="panel analytics-card"><small>${esc(label)}</small><strong>${esc(value)}</strong><span>${esc(sub)}</span>${progress===null?'':`<div class="analytics-bar"><i style="width:${Math.max(0,Math.min(100,progress))}%"></i></div>`}</div>`}
function renderAnalytics(){
  const host=$('learning-analytics');if(!host)return;const profile=guidance.snapshot().profile,a=sessions.analytics(profile),max=Math.max(1,...a.trend7.map(d=>d.minutes));
  const mix=a.activityMix.length?a.activityMix.slice(0,6).map(x=>`<div class="activity-row"><div><strong>${esc(viewLabel(x.view))}</strong><small>${x.minutes} active min</small></div><span>${x.percent}%</span></div>`).join(''):'<p class="session-time-note">No foreground session time recorded yet.</p>';
  const history=a.history.length?a.history.map(s=>`<div class="history-row"><div><strong>${new Date(s.startedAt).toLocaleDateString()}</strong><small>${esc(s.finishReason==='completed'?'Plan completed':'Ended manually')} · ${s.completedTasks}/${s.totalTasks} tasks</small></div><span>${engagedLabel(s.engagedSeconds)}</span></div>`).join(''):'<p class="session-time-note">Completed sessions will appear here.</p>';
  host.innerHTML=`<div class="analytics-panel"><div class="analytics-grid">${analyticsCard('This week',`${a.week.minutes} / ${a.week.targetMinutes} min`,`${a.week.studyDays} / ${a.week.targetDays} study days`,a.week.progressPercent)}${analyticsCard('Task completion',`${a.recent28.completionPercent}%`,'Recent 28-day session tasks')}${analyticsCard('Average session',`${a.recent28.averageSessionMinutes} min`,`${a.recent28.sessions} completed sessions`)}${analyticsCard('Study-day coverage',`${a.recent28.consistencyPercent}%`,`${a.recent28.studyDays} / ${a.recent28.targetStudyDays} target days`)}</div>${a.workloadSuggestion?`<div class="panel workload-suggestion"><strong>Workload fit suggestion</strong><p>${esc(a.workloadSuggestion.reason)}</p><button class="btn" id="apply-workload">Use ${a.workloadSuggestion.suggestedMinutes}-minute sessions</button></div>`:''}<div class="analytics-two-col"><div class="panel"><h3>Last 7 days</h3><p class="session-time-note">Foreground active minutes, not time since the tab was opened.</p><div class="trend-bars">${a.trend7.map(d=>`<div class="trend-day"><div title="${esc(d.date)} · ${d.minutes} min"><i style="height:${Math.max(2,Math.round(d.minutes/max*100))}%"></i></div><span>${new Date(`${d.date}T12:00:00`).toLocaleDateString(undefined,{weekday:'short'})}</span></div>`).join('')}</div></div><div class="panel"><h3>Activity mix</h3><div class="activity-mix">${mix}</div></div></div><div class="panel analytics-panel"><h3>Recent sessions</h3><div class="session-history">${history}</div></div></div>`;
  $('apply-workload')?.addEventListener('click',()=>{guidance.saveProfile({sessionMinutes:a.workloadSuggestion.suggestedMinutes});window.KOINE_GUIDANCE_UI?.render?.();renderAll()});
}
function renderAll(){renderToday();renderAnalytics()}
window.KOINE_SESSION_UI={render:renderAll};
let lastPulse=performance.now(),renderCounter=0;
function pulse(){const now=performance.now(),delta=Math.min(10,Math.max(0,Math.round((now-lastPulse)/1000)));lastPulse=now;const active=sessions.getActiveSession();if(document.visibilityState==='visible'&&active?.status==='active'&&delta>0){const view=document.querySelector('.view.active')?.id||active.contextView||'today';sessions.recordEngagement(delta,view);if(++renderCounter%3===0)renderAll()}}
document.addEventListener('visibilitychange',()=>{lastPulse=performance.now()});setInterval(pulse,5000);
renderAll();
})();