(()=>{
'use strict';
const data=window.KOINE_SYNTAX_DATA,api=window.KoineSyntax,learning=window.KOINE_LEARNING_ENGINE;if(!data||!api||!learning)return;
const engine=new api.SyntaxEngine({data,learningEngine:learning});window.KOINE_SYNTAX_ENGINE=engine;
if(typeof titles!=='undefined')titles.syntax=['Syntax','Clause relationships, discourse, and translation structure.'];
const nav=document.querySelector('.nav'),readBtn=nav?.querySelector('[data-view="read"]');if(nav&&!nav.querySelector('[data-view="syntax"]')){const b=document.createElement('button');b.dataset.view='syntax';b.textContent='Syntax';readBtn?.after(b);b.addEventListener('click',()=>openView('syntax'));}
const main=document.querySelector('.content'),read=document.querySelector('#read'),section=document.createElement('section');section.id='syntax';section.className='view';section.innerHTML=`
<div class="eyebrow">Syntax & translation laboratory · BG7</div><h1>Read relationships, not isolated words.</h1><p class="lede">Work from the canonical Greek passage to clause structure, then draft English without collapsing syntax into one-word glosses.</p>
<div class="syntax-toolbar panel"><label>Unit<select id="syntax-unit"><option value="all">38–44 · all syntax</option>${Object.entries(data.units).map(([id,n])=>`<option value="${id}">${id} · ${n}</option>`).join('')}</select></label><label>Mode<select id="syntax-type"><option value="all">Mixed</option>${data.types.map(t=>`<option value="${t}">${t}</option>`).join('')}</select></label><button class="btn" id="syntax-reader-match">Use reader location</button><button class="btn primary" id="syntax-next">Next exercise</button></div>
<div class="syntax-layout">
<article class="panel syntax-work"><div class="syntax-meta"><span id="syntax-ref">—</span><span id="syntax-unit-state">—</span></div><div class="greek syntax-passage" id="syntax-passage">Loading passage…</div><h2 id="syntax-prompt">—</h2><div class="syntax-options" id="syntax-options"></div><div class="feedback" id="syntax-feedback"></div><div class="syntax-actions"><button class="btn" id="syntax-hint">Hint</button><button class="btn" id="syntax-diagram">Structure</button><button class="btn" id="syntax-reveal">Explain</button></div><div class="syntax-help" id="syntax-help" hidden></div><div class="syntax-diagram" id="syntax-diagram-box" hidden></div></article>
<aside class="panel syntax-side"><div class="eyebrow">Session</div><div class="syntax-stats"><div><span>Accuracy</span><strong id="syntax-accuracy">—</strong></div><div><span>Attempts</span><strong id="syntax-attempts">0</strong></div><div><span>Drafts</span><strong id="syntax-drafts">0</strong></div><div><span>Source</span><strong>Reviewed</strong></div></div><p>The Greek text and morphology come from BG6. Syntactic labels are separately reviewed Koinē Path annotations.</p></aside>
</div>
<div class="panel syntax-translation"><div class="section-head"><div><h2>Translation bench</h2><p>Draft first. Preserve relationships before polishing English.</p></div></div><textarea id="syntax-draft" placeholder="Write your own structural translation of the displayed passage. Do not worry about elegance on the first pass."></textarea><div class="syntax-translation-actions"><button class="btn" id="syntax-save-draft">Save draft</button><span id="syntax-draft-status"></span></div><ol><li>Identify the main finite predication.</li><li>Preserve subordinate, participial, infinitival, and prepositional relationships.</li><li>Revise into natural English only after the structure is clear.</li><li>Re-check the revision against the Greek rather than against a preferred English wording.</li></ol></div>`;
main?.insertBefore(section,read?.nextSibling||null);
const $=s=>section.querySelector(s);let current=null,assistance='none',answered=false;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function statRender(){const s=engine.stats();$('#syntax-accuracy').textContent=s.accuracy==null?'—':`${s.accuracy}%`;$('#syntax-attempts').textContent=s.attempts;$('#syntax-drafts').textContent=s.drafts;}
function stateLabel(ex){const u=learning.getUnit(ex.unitId);return u?.accessible?`Unit ${ex.unitId} · ${u.status}`:`Unit ${ex.unitId} · preview only`;}
async function show(ex){if(!ex)return;current=ex;assistance='none';answered=false;$('#syntax-feedback').textContent='';$('#syntax-feedback').className='feedback';$('#syntax-help').hidden=true;$('#syntax-diagram-box').hidden=true;$('#syntax-help').textContent='';$('#syntax-diagram-box').innerHTML='';$('#syntax-ref').textContent=`${ex.ref.book} ${ex.ref.chapter}:${ex.ref.verse} · ${ex.type}`;$('#syntax-unit-state').textContent=stateLabel(ex);$('#syntax-prompt').textContent=ex.prompt;$('#syntax-passage').textContent='Loading canonical Greek…';$('#syntax-options').innerHTML=ex.choices.map((c,i)=>`<button data-choice="${i}">${esc(c)}</button>`).join('');$('#syntax-options').querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>answer(Number(b.dataset.choice))));const d=engine.draft(ex.id);$('#syntax-draft').value=d.text||'';$('#syntax-draft-status').textContent=d.updatedAt?'Saved draft loaded.':'';try{const p=await engine.passage(ex);$('#syntax-passage').textContent=p.text;}catch(err){$('#syntax-passage').textContent=`Corpus passage unavailable: ${err.message}`;}}
function answer(choice){if(!current||answered)return;answered=true;const r=engine.answer(current.id,choice,{assistance});$('#syntax-options').querySelectorAll('button').forEach((b,i)=>{b.disabled=true;if(i===current.answer)b.classList.add('correct');if(i===choice&&!r.correct)b.classList.add('wrong')});$('#syntax-feedback').textContent=r.correct?'Correct. The structural relation is recorded.':`Not yet. ${current.explanation}`;$('#syntax-feedback').className='feedback '+(r.correct?'good':'bad');statRender();if(window.renderLearningEngineUI)window.renderLearningEngineUI();}
$('#syntax-hint').addEventListener('click',()=>{if(!current)return;assistance=assistance==='none'?'hint':assistance;engine.recordAssistance(current,'hint');$('#syntax-help').hidden=false;$('#syntax-help').textContent=current.hint;});
$('#syntax-diagram').addEventListener('click',()=>{if(!current)return;assistance=assistance==='reveal'?'reveal':'diagram';engine.recordAssistance(current,'diagram');$('#syntax-diagram-box').hidden=false;$('#syntax-diagram-box').innerHTML=current.structure.map((x,i)=>`<div style="--depth:${Math.min(3,(x.match(/^\s+/)?.[0].length||0))}">${esc(x.trim())}</div>`).join('');});
$('#syntax-reveal').addEventListener('click',()=>{if(!current)return;assistance='reveal';engine.recordAssistance(current,'reveal');$('#syntax-help').hidden=false;$('#syntax-help').textContent=current.explanation;$('#syntax-diagram-box').hidden=false;$('#syntax-diagram-box').innerHTML=current.structure.map(x=>`<div>${esc(x)}</div>`).join('');});
function filters(){return{unit:$('#syntax-unit').value,type:$('#syntax-type').value}}
$('#syntax-next').addEventListener('click',()=>show(engine.next(filters())));$('#syntax-unit').addEventListener('change',()=>show(engine.next(filters())));$('#syntax-type').addEventListener('change',()=>show(engine.next(filters())));
$('#syntax-save-draft').addEventListener('click',()=>{if(!current)return;engine.saveDraft(current.id,$('#syntax-draft').value);$('#syntax-draft-status').textContent='Draft saved locally. Drafting itself does not grant mastery.';statRender();});
$('#syntax-reader-match').addEventListener('click',()=>{const b=document.querySelector('#reader-book')?.value,c=Number(document.querySelector('#reader-chapter')?.value),v=Number(document.querySelector('#reader-text .word.selected')?.dataset.verse)||null;if(!b||!c){$('#syntax-feedback').textContent='Open a corpus passage in Read first.';return}const matches=engine.exercisesForLocation(b,c,v);if(matches.length)show(matches[0]);else{$('#syntax-feedback').textContent=`No reviewed BG7 exercise is registered for ${b} ${c}${v?':'+v:''} yet.`;$('#syntax-feedback').className='feedback';}});
statRender();show(engine.next());
})();