(()=>{
  const seed=window.KOINE_VOCAB_SEED,api=window.KoineVocabulary,learning=window.KOINE_LEARNING_ENGINE,greek=window.KOINE_GREEK_DATA;
  if(!seed||!api)return;
  const engine=new api.VocabularyEngine({seed,learningEngine:learning,greekData:greek});window.KOINE_VOCAB_ENGINE=engine;
  if(typeof titles!=='undefined')titles.vocab=['Vocabulary','Frequency-aware lexical learning and spaced review.'];
  const nav=document.querySelector('.nav'),drill=nav?.querySelector('[data-view="drill"]');
  if(nav&&!nav.querySelector('[data-view="vocab"]')){const b=document.createElement('button');b.dataset.view='vocab';b.textContent='Vocabulary';drill?.after(b);b.addEventListener('click',()=>openView('vocab'));}
  const main=document.querySelector('.content'),progress=document.querySelector('#progress');
  const section=document.createElement('section');section.id='vocab';section.className='view';section.innerHTML=`
    <div class="eyebrow">Vocabulary & SRS · BG5</div><h1>Learn words for reading, not word equations.</h1>
    <p class="lede">Frequency determines priority. Reference glosses prompt recall; passage context still determines sense.</p>
    <div class="vocab-layout">
      <article class="panel vocab-card">
        <div><div class="morph-meta"><span id="vocab-type">Lemma recognition</span><span id="vocab-rank">Rank —</span></div><div class="greek vocab-front" id="vocab-front">—</div><p class="vocab-prompt" id="vocab-prompt">Loading vocabulary corpus…</p><div class="vocab-answer" id="vocab-answer" hidden><strong id="vocab-back"></strong><p id="vocab-context"></p><small id="vocab-meta"></small></div></div>
        <div><button class="btn primary" id="vocab-reveal">Reveal after recall</button><div class="vocab-rating" id="vocab-rating" hidden><button class="btn" data-rate="again">Again<small>forgot</small></button><button class="btn" data-rate="hard">Hard<small>barely</small></button><button class="btn" data-rate="good">Good<small>recalled</small></button><button class="btn" data-rate="easy">Easy<small>immediate</small></button></div></div>
      </article>
      <aside class="panel"><div class="eyebrow">Daily queue</div><div class="vocab-stats"><div><span>Due</span><strong id="vocab-due">0</strong></div><div><span>Cards</span><strong id="vocab-cards">0</strong></div><div><span>Core loaded</span><strong id="vocab-core">—</strong></div><div><span>Target rank</span><strong id="vocab-target">—</strong></div><div><span>Learning</span><strong id="vocab-learning">0</strong></div><div><span>Leeches</span><strong id="vocab-leeches">0</strong></div></div><p class="vocab-source-note" id="vocab-source">Loading pinned frequency data…</p></aside>
    </div>
    <div class="panel vocab-search"><div class="section-head"><div><h2>Lexeme browser</h2><p>Search the loaded 1,200-word core/stretch corpus and add a word deliberately.</p></div></div><div class="vocab-search-row"><input id="vocab-search-input" aria-label="Search Greek vocabulary" placeholder="Greek lemma or reference gloss"><button class="btn" id="vocab-search-btn">Search</button></div><div id="vocab-results" class="vocab-results"></div></div>`;
  main?.insertBefore(section,progress||null);
  const $=s=>section.querySelector(s);let current=null,revealed=false;
  function typeLabel(c){return c?.type==='form-to-lemma'?'Form → lemma':'Lemma → reference gloss'}
  function stats(){const s=engine.stats();$('#vocab-due').textContent=s.due;$('#vocab-cards').textContent=s.cards;$('#vocab-core').textContent=`${Math.min(s.coreLoaded,1000)}/1000`;$('#vocab-target').textContent=s.targetRank;$('#vocab-learning').textContent=s.learning;$('#vocab-leeches').textContent=s.leeches;$('#vocab-source').textContent=s.sourceRemote?`NT-wide frequency loaded: ranks 1–1200 · pinned core-gnt-vocab ${seed.source.commit.slice(0,7)} · frequency based on MorphGNT. Reference glosses are prompts, not contextual definitions.`:`Fallback seed active; online frequency corpus could not yet be loaded.`;}
  function renderCard(card){current=card;revealed=false;$('#vocab-answer').hidden=true;$('#vocab-rating').hidden=true;$('#vocab-reveal').hidden=false;if(!card){$('#vocab-front').textContent='Queue clear';$('#vocab-prompt').textContent='No card is due and today’s new-card limit has been reached.';$('#vocab-type').textContent='Complete';$('#vocab-rank').textContent='';return}$('#vocab-front').textContent=card.front;$('#vocab-type').textContent=typeLabel(card);$('#vocab-rank').textContent=card.rank<=1200?`Rank ${card.rank} · ${card.band}`:'Passage word';$('#vocab-prompt').textContent=card.type==='form-to-lemma'?'Recall the lemma before revealing.':'Recall a useful reading gloss before revealing.';$('#vocab-back').textContent=card.back;$('#vocab-context').textContent=card.passages?.length?`Seen in: ${card.passages.join(', ')}`:'';$('#vocab-meta').textContent=`${card.count?card.count+' NT occurrences · ':''}${card.state} · interval ${Math.round(card.intervalDays*10)/10}d${card.leech?' · leech':''}`;}
  function next(){renderCard(engine.nextCard());stats()}
  $('#vocab-reveal').addEventListener('click',()=>{if(!current)return;revealed=true;$('#vocab-answer').hidden=false;$('#vocab-rating').hidden=false;$('#vocab-reveal').hidden=true});
  $('#vocab-rating').querySelectorAll('[data-rate]').forEach(b=>b.addEventListener('click',()=>{if(!current||!revealed)return;engine.rate(current.id,b.dataset.rate);if(window.renderLearningEngine)window.renderLearningEngine();next()}));
  function search(){const q=$('#vocab-search-input').value.trim(),results=q?engine.search(q):engine.corpus.slice(0,20);$('#vocab-results').innerHTML=results.map(e=>`<div class="vocab-result"><span><strong class="greek">${e.lemma}</strong><br><small>${e.referenceGloss||'—'}</small></span><small>#${e.rank} · ${e.count}</small><button class="btn" data-add-lemma="${e.lemma}">Learn</button></div>`).join('');$('#vocab-results').querySelectorAll('[data-add-lemma]').forEach(b=>b.addEventListener('click',()=>{engine.ensureLemma(b.dataset.addLemma,{source:'manual'});stats();next()}))}
  $('#vocab-search-btn').addEventListener('click',search);$('#vocab-search-input').addEventListener('keydown',e=>{if(e.key==='Enter')search()});
  const panel=document.querySelector('.word-panel');if(panel&&!panel.querySelector('#add-vocab')){const b=document.createElement('button');b.id='add-vocab';b.className='btn reader-vocab-btn';b.textContent='Learn vocabulary';panel.appendChild(b);b.addEventListener('click',()=>{if(!selectedWord?.token)return;engine.addToken(selectedWord.token,{passageId:'John.1.1'});b.textContent='Added to vocabulary';stats()})}
  engine.loadCorpus().then(()=>{stats();search();next()});stats();next();
})();