(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.KoineVocabulary=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const STATE_KEY='koine-path-vocab-srs-v1',CORPUS_KEY='koine-path-vocab-corpus-v1',SCHEMA=1,DAILY_NEW=12,CORE=1000,STRETCH=1200,RATINGS=['again','hard','good','easy'];
function clone(v){return JSON.parse(JSON.stringify(v))}function safe(v){try{return JSON.parse(v)}catch{return null}}function iso(d){return new Date(d).toISOString()}function addMinutes(d,m){return iso(new Date(new Date(d).getTime()+m*60000))}function addDays(d,n){return iso(new Date(new Date(d).getTime()+n*86400000))}function dayKey(d){return iso(d).slice(0,10)}function norm(s){return String(s||'').normalize('NFC')}
class MemoryStorage{constructor(seed={}){this.m=new Map(Object.entries(seed))}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}}
function band(rank){return rank<=100?'F1':rank<=300?'F2':rank<=600?'F3':rank<=1000?'F4':'F5'}function unitForRank(rank){if(rank<=20)return 4;if(rank<=80)return 10;if(rank<=180)return 16;if(rank<=320)return 23;if(rank<=450)return 29;if(rank<=600)return 37;if(rank<=800)return 44;return 50}
function parseTsv(text,limit=STRETCH){const lines=String(text).trim().split(/\r?\n/),out=[];for(let i=1;i<lines.length&&out.length<limit;i++){const [lemma,count,...rest]=lines[i].split('\t');if(!lemma||!count)continue;const rank=out.length+1;out.push({lemma:norm(lemma),count:Number(count),referenceGloss:rest.join('\t').trim(),rank,band:band(rank),source:'core-gnt-vocab'})}return out}
function initial(){return{schemaVersion:SCHEMA,cards:{},dailyNew:{},history:[],settings:{dailyNewLimit:DAILY_NEW},createdAt:null,updatedAt:null}}
function blankCard(base){return{...base,state:'new',dueAt:base.dueAt,intervalDays:0,ease:2.5,reps:0,lapses:0,leech:false,lastRating:null,lastReviewedAt:null,suspended:false}}
class VocabularyEngine{
 constructor({seed,learningEngine=null,greekData=null,storage=null,clock=()=>new Date(),fetchFn=null}={}){if(!seed)throw new Error('VocabularyEngine requires vocabulary seed data.');this.seed=seed;this.learningEngine=learningEngine;this.greekData=greekData;this.storage=storage||((typeof localStorage!=='undefined')?localStorage:new MemoryStorage());this.clock=clock;this.fetchFn=fetchFn||((typeof fetch!=='undefined')?fetch.bind(globalThis):null);this.corpus=this.loadCachedCorpus()||seed.entries.map((e,i)=>({...e,rank:e.rank||i+1,band:band(e.rank||i+1),source:'fallback-seed'}));this.index=new Map(this.corpus.map(e=>[norm(e.lemma),e]));this.state={...initial(),...(safe(this.storage.getItem(STATE_KEY))||{})};this.state.createdAt=this.state.createdAt||iso(this.clock());this.refreshCards();this.persist()}
 persist(){this.state.updatedAt=iso(this.clock());this.storage.setItem(STATE_KEY,JSON.stringify(this.state))}loadCachedCorpus(){const c=safe(this.storage.getItem(CORPUS_KEY));return c&&c.commit===this.seed.source.commit&&Array.isArray(c.entries)?c.entries:null}
 refreshCards(){Object.values(this.state.cards).forEach(c=>{const e=this.entry(c.lemma);if(!e)return;c.rank=e.rank;c.count=e.count;c.band=e.band;c.unitId=unitForRank(e.rank);if(c.type==='lemma-recognition'&&(c.back==='Reference gloss not yet loaded.'||c.source==='frequency'||c.source==='reader'))c.back=e.referenceGloss||c.back})}
 async loadCorpus(){if(!this.fetchFn)return this.corpus;try{const r=await this.fetchFn(this.seed.source.url);if(!r.ok)throw new Error('frequency fetch failed');const entries=parseTsv(await r.text(),STRETCH);if(entries.length<CORE)throw new Error('frequency corpus shorter than core target');this.corpus=entries;this.index=new Map(entries.map(e=>[e.lemma,e]));this.storage.setItem(CORPUS_KEY,JSON.stringify({commit:this.seed.source.commit,entries}));this.refreshCards();this.persist();return entries}catch{return this.corpus}}
 entry(lemma){return this.index.get(norm(lemma))||null}targetRank(){if(!this.learningEngine)return 80;const d=this.learningEngine.getDashboard(),stage=d.currentStage;return Math.min(STRETCH,stage?.vocabTarget||80)}cardId(type,key){return `vocab.${type}.${norm(key)}`}
 ensureLemma(lemma,{source='frequency',passageId=null}={}){lemma=norm(lemma);const e=this.entry(lemma)||{count:null,rank:STRETCH+1,band:'F5',referenceGloss:'Reference gloss not yet loaded.'},id=this.cardId('lemma',lemma);if(!this.state.cards[id])this.state.cards[id]=blankCard({id,type:'lemma-recognition',lemma,front:lemma,back:e.referenceGloss||'Reference gloss not yet reviewed.',rank:e.rank,count:e.count,band:e.band,unitId:unitForRank(e.rank),source,passages:passageId?[passageId]:[],dueAt:iso(this.clock())});else if(passageId&&!this.state.cards[id].passages.includes(passageId))this.state.cards[id].passages.push(passageId);this.persist();return clone(this.state.cards[id])}
 addToken(token,{passageId='reader'}={}){if(!token)return[];const e=this.entry(token.lemma)||{rank:STRETCH+1,count:null,band:'F5'},cards=[this.ensureLemma(token.lemma,{source:'reader',passageId})],formId=this.cardId('form',token.id||token.word);if(!this.state.cards[formId])this.state.cards[formId]=blankCard({id:formId,type:'form-to-lemma',lemma:norm(token.lemma),front:token.word||token.text,back:norm(token.lemma),rank:e.rank,count:e.count,band:e.band,unitId:unitForRank(e.rank),source:'reader',passages:[passageId],dueAt:iso(this.clock())});cards.push(clone(this.state.cards[formId]));const ann=this.greekData?.learningAnnotations?.[token.id],glosses=ann?.glosses||[];if(glosses.length){const contextId=this.cardId('context',`${token.id}.${passageId}`);if(!this.state.cards[contextId])this.state.cards[contextId]=blankCard({id:contextId,type:'context-sense',lemma:norm(token.lemma),front:`${token.word||token.text} · ${passageId}`,back:`Passage learning gloss: ${glosses.join(' / ')}`,rank:e.rank,count:e.count,band:e.band,unitId:unitForRank(e.rank),source:'reader-context',passages:[passageId],dueAt:iso(this.clock())});cards.push(clone(this.state.cards[contextId]))}this.persist();return cards}
 introduceNext(){const today=dayKey(this.clock()),used=this.state.dailyNew[today]||0;if(used>=this.state.settings.dailyNewLimit)return null;const target=this.targetRank(),seen=new Set(Object.values(this.state.cards).filter(c=>c.type==='lemma-recognition').map(c=>c.lemma)),candidate=this.corpus.find(e=>e.rank<=target&&!seen.has(e.lemma));if(!candidate)return null;this.state.dailyNew[today]=used+1;return this.ensureLemma(candidate.lemma,{source:'frequency'})}
 due(){const now=new Date(this.clock());return Object.values(this.state.cards).filter(c=>new Date(c.dueAt)<=now&&!c.suspended).sort((a,b)=>new Date(a.dueAt)-new Date(b.dueAt)||a.rank-b.rank)}nextCard(){return clone(this.due()[0]||this.introduceNext())}
 schedule(card,rating){const now=this.clock();card.reps++;card.lastRating=rating;card.lastReviewedAt=iso(now);if(rating==='again'){card.lapses++;card.state=card.state==='new'?'learning':'relearning';card.intervalDays=Math.max(.01,(card.intervalDays||1)*.25);card.dueAt=addMinutes(now,10);card.ease=Math.max(1.3,card.ease-.2)}else if(rating==='hard'){card.state=card.state==='new'?'learning':'review';card.intervalDays=Math.max(.25,(card.intervalDays||.25)*1.2);card.dueAt=addDays(now,card.intervalDays);card.ease=Math.max(1.3,card.ease-.05)}else if(rating==='good'){card.state='review';card.intervalDays=card.intervalDays<1?1:Math.max(1,card.intervalDays*card.ease);card.dueAt=addDays(now,card.intervalDays)}else{card.state='review';card.ease=Math.min(3.2,card.ease+.15);card.intervalDays=card.intervalDays<1?4:Math.max(4,card.intervalDays*card.ease*1.3);card.dueAt=addDays(now,card.intervalDays)}card.leech=card.lapses>=6;return card}
 rate(id,rating){if(!RATINGS.includes(rating))throw new Error('Unknown SRS rating');const card=this.state.cards[id];if(!card)throw new Error('Unknown vocabulary card');this.schedule(card,rating);this.state.history.push({cardId:id,rating,at:iso(this.clock())});if(this.state.history.length>500)this.state.history.splice(0,this.state.history.length-500);if(this.learningEngine){const u=this.learningEngine.getUnit(card.unitId),correct=rating!=='again';if(u?.accessible)this.learningEngine.recordEvidence({unitId:card.unitId,dimension:'recognition',correct,hintLevel:'none',errorType:correct?null:'vocabulary_retrieval',itemId:id,source:'vocabulary-srs',confidence:.55});else this.learningEngine.recordExposure({unitId:card.unitId,itemId:id,source:'vocabulary-srs'})}this.persist();return clone(card)}
 suspend(id,on=true){if(this.state.cards[id]){this.state.cards[id].suspended=on;this.persist()}}stats(){const cards=Object.values(this.state.cards),due=this.due();return{cards:cards.length,due:due.length,new:cards.filter(c=>c.state==='new').length,learning:cards.filter(c=>['learning','relearning'].includes(c.state)).length,review:cards.filter(c=>c.state==='review').length,leeches:cards.filter(c=>c.leech).length,coreLoaded:this.corpus.filter(e=>e.rank<=CORE).length,stretchLoaded:this.corpus.filter(e=>e.rank<=STRETCH).length,targetRank:this.targetRank(),sourceRemote:this.corpus.length>=CORE}}search(q,limit=20){q=norm(q).toLowerCase();return this.corpus.filter(e=>e.lemma.toLowerCase().includes(q)||(e.referenceGloss||'').toLowerCase().includes(q)).slice(0,limit).map(clone)}
}
return{STATE_KEY,CORPUS_KEY,SCHEMA,CORE,STRETCH,RATINGS,MemoryStorage,parseTsv,band,unitForRank,VocabularyEngine};
});